// Auto-generated by idl-c.fluid

static const struct FieldDef clTextFlags[] = {
   { "Secret", 0x00020000 },
   { "PreserveBkgd", 0x00010000 },
   { "AreaSelected", 0x00000200 },
   { "GlobalEditing", 0x00000100 },
   { "SingleSelect", 0x00001000 },
   { "Disabled", 0x00002000 },
   { "Overwrite", 0x00000004 },
   { "Select", 0x00001800 },
   { "EnterTab", 0x00008000 },
   { "ForceCaps", 0x00000080 },
   { "AutoClear", 0x00000002 },
   { "Edit", 0x00000001 },
   { "Stretch", 0x00200000 },
   { "Wordwrap", 0x00000010 },
   { "AutoSelect", 0x00080000 },
   { "TabKey", 0x00040000 },
   { "Password", 0x00020000 },
   { "MultiSelect", 0x00000800 },
   { "Variable", 0x00000040 },
   { "StrTranslate", 0x00100000 },
   { "History", 0x00000020 },
   { "NoSysKeys", 0x00000400 },
   { "Background", 0x00004000 },
   { "TabEntry", 0x00000008 },
   { "Commandline", 0x00000023 },
   { NULL, 0 }
};

FDEF maAddLine[] = { { "Line", FD_LONG }, { "String", FD_BUFFER|FD_STR }, { "Length", FD_LONG|FD_BUFSIZE }, { 0, 0 } };
FDEF maDeleteLine[] = { { "Line", FD_LONG }, { 0, 0 } };
FDEF maGetLine[] = { { "Line", FD_LONG }, { "Buffer", FD_BUFFER|FD_STR }, { "Length", FD_LONG|FD_BUFSIZE }, { 0, 0 } };
FDEF maReplaceLine[] = { { "Line", FD_LONG }, { "String", FD_BUFFER|FD_STR }, { "Length", FD_LONG|FD_BUFSIZE }, { 0, 0 } };
FDEF maSelectArea[] = { { "Row", FD_LONG }, { "Column", FD_LONG }, { "EndRow", FD_LONG }, { "EndColumn", FD_LONG }, { 0, 0 } };
FDEF maSetFont[] = { { "Face", FD_STR }, { 0, 0 } };

static const struct MethodArray clTextMethods[] = {
   { -1, (APTR)TEXT_AddLine, "AddLine", maAddLine, sizeof(struct txtAddLine) },
   { -2, (APTR)TEXT_DeleteLine, "DeleteLine", maDeleteLine, sizeof(struct txtDeleteLine) },
   { -3, (APTR)TEXT_GetLine, "GetLine", maGetLine, sizeof(struct txtGetLine) },
   { -4, (APTR)TEXT_ReplaceLine, "ReplaceLine", maReplaceLine, sizeof(struct txtReplaceLine) },
   { -5, (APTR)TEXT_SelectAreaText, "SelectArea", maSelectArea, sizeof(struct txtSelectArea) },
   { -6, (APTR)TEXT_SetFont, "SetFont", maSetFont, sizeof(struct txtSetFont) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clTextActions[] = {
   { AC_ActionNotify, (APTR)TEXT_ActionNotify },
   { AC_Clear, (APTR)TEXT_Clear },
   { AC_Clipboard, (APTR)TEXT_Clipboard },
   { AC_DataFeed, (APTR)TEXT_DataFeed },
   { AC_Disable, (APTR)TEXT_Disable },
   { AC_Draw, (APTR)TEXT_Draw },
   { AC_Enable, (APTR)TEXT_Enable },
   { AC_Focus, (APTR)TEXT_Focus },
   { AC_Free, (APTR)TEXT_Free },
   { AC_Hide, (APTR)TEXT_Hide },
   { AC_Init, (APTR)TEXT_Init },
   { AC_NewObject, (APTR)TEXT_NewObject },
   { AC_SaveToObject, (APTR)TEXT_SaveToObject },
   { AC_ScrollToPoint, (APTR)TEXT_ScrollToPoint },
   { AC_Show, (APTR)TEXT_Show },
   { 0, 0 }
};

