// Auto-generated by idl-c.fluid

static const struct FieldDef clInputFlags[] = {
   { "Disabled", 0x00000001 },
   { "Commandline", 0x00000002 },
   { "SelectText", 0x00000004 },
   { "Secret", 0x00000008 },
   { "FixedLabelWidth", 0x00000010 },
   { "FixedInputWidth", 0x00000020 },
   { "EnterTab", 0x00000040 },
   { NULL, 0 }
};

static const struct ActionArray clInputActions[] = {
   { AC_ActionNotify, (APTR)INPUT_ActionNotify },
   { AC_Activate, (APTR)INPUT_Activate },
   { AC_Disable, (APTR)INPUT_Disable },
   { AC_Enable, (APTR)INPUT_Enable },
   { AC_Focus, (APTR)INPUT_Focus },
   { AC_Free, (APTR)INPUT_Free },
   { AC_Hide, (APTR)INPUT_Hide },
   { AC_Init, (APTR)INPUT_Init },
   { AC_MoveToBack, (APTR)INPUT_MoveToBack },
   { AC_MoveToFront, (APTR)INPUT_MoveToFront },
   { AC_NewObject, (APTR)INPUT_NewObject },
   { AC_Redimension, (APTR)INPUT_Redimension },
   { AC_Resize, (APTR)INPUT_Resize },
   { AC_Show, (APTR)INPUT_Show },
   { 0, 0 }
};

