// Auto-generated by idl-c.fluid

static const struct FieldDef clTabFocusFlags[] = {
   { "LocalFocus", 0x00000001 },
   { "ChildFocus", 0x00000002 },
   { "LimitToList", 0x00000004 },
   { NULL, 0 }
};

FDEF maAddObject[] = { { "Object", FD_OBJECTID }, { 0, 0 } };
FDEF maInsertObject[] = { { "Index", FD_LONG }, { "Object", FD_OBJECTID }, { 0, 0 } };
FDEF maRemoveObject[] = { { "Object", FD_OBJECTID }, { 0, 0 } };
FDEF maSetObject[] = { { "Index", FD_LONG }, { "Object", FD_OBJECTID }, { 0, 0 } };

static const struct MethodArray clTabFocusMethods[] = {
   { -1, (APTR)TABFOCUS_AddObject, "AddObject", maAddObject, sizeof(struct tabAddObject) },
   { -2, (APTR)TABFOCUS_InsertObject, "InsertObject", maInsertObject, sizeof(struct tabInsertObject) },
   { -3, (APTR)TABFOCUS_RemoveObject, "RemoveObject", maRemoveObject, sizeof(struct tabRemoveObject) },
   { -4, (APTR)TABFOCUS_SetObject, "SetObject", maSetObject, sizeof(struct tabSetObject) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clTabFocusActions[] = {
   { AC_Activate, (APTR)TABFOCUS_Activate },
   { AC_Clear, (APTR)TABFOCUS_Clear },
   { AC_Free, (APTR)TABFOCUS_Free },
   { AC_Init, (APTR)TABFOCUS_Init },
   { 0, 0 }
};

