// Auto-generated by idl-c.fluid

static const struct FieldDef clImageFlags[] = {
   { "NoDraw", 0x00000100 },
   { "Fixed", 0x00000080 },
   { "Enlarge", 0x00000001 },
   { "NoFail", 0x00000010 },
   { "Shrink", 0x00000002 },
   { "SolidBlend", 0x00000004 },
   { "Fit", 0x00000040 },
   { "NoBlend", 0x00000004 },
   { "FixedSize", 0x00000080 },
   { "Stretch", 0x00000003 },
   { "Scalable", 0x00000200 },
   { "Sticky", 0x00000008 },
   { "11Ratio", 0x00000020 },
   { NULL, 0 }
};

static const struct ActionArray clImageActions[] = {
   { AC_DataFeed, (APTR)IMAGE_DataFeed },
   { AC_Free, (APTR)IMAGE_Free },
   { AC_Hide, (APTR)IMAGE_Hide },
   { AC_Init, (APTR)IMAGE_Init },
   { AC_Move, (APTR)IMAGE_Move },
   { AC_MoveToFront, (APTR)IMAGE_MoveToFront },
   { AC_MoveToPoint, (APTR)IMAGE_MoveToPoint },
   { AC_NewObject, (APTR)IMAGE_NewObject },
   { AC_ScrollToPoint, (APTR)IMAGE_ScrollToPoint },
   { AC_Show, (APTR)IMAGE_Show },
   { 0, 0 }
};

