// Auto-generated by idl-c.fluid

static const struct FieldDef clPictureFlags[] = {
   { "ResizeX", 0x00000001 },
   { "NoPalette", 0x00000002 },
   { "Scalable", 0x00000004 },
   { "ResizeY", 0x00000008 },
   { "Resize", 0x00000009 },
   { "New", 0x00000010 },
   { "Mask", 0x00000020 },
   { "Alpha", 0x00000040 },
   { "Lazy", 0x00000080 },
   { "ForceAlpha32", 0x00000100 },
   { NULL, 0 }
};

#undef MOD_IDL
#define MOD_IDL "c.PCF:ALPHA=0x40,FORCE_ALPHA_32=0x100,LAZY=0x80,MASK=0x20,NEW=0x10,NO_PALETTE=0x2,RESIZE=0x9,RESIZE_X=0x1,RESIZE_Y=0x8,SCALABLE=0x4\n"
