// Auto-generated by idl-c.fluid

FDEF maAddCommand[] = { { "PathCommand:Commands", FD_BUFFER|FD_PTR|FD_STRUCT }, { "Size", FD_LONG|FD_BUFSIZE }, { 0, 0 } };
FDEF maRemoveCommand[] = { { "Index", FD_LONG }, { "Total", FD_LONG }, { 0, 0 } };
FDEF maSetCommand[] = { { "Index", FD_LONG }, { "PathCommand:Command", FD_BUFFER|FD_PTR|FD_STRUCT }, { "Size", FD_LONG|FD_BUFSIZE }, { 0, 0 } };
FDEF maGetCommand[] = { { "Index", FD_LONG }, { "PathCommand:Command", FD_PTR|FD_STRUCT|FD_RESULT }, { 0, 0 } };
FDEF maSetCommandList[] = { { "Commands", FD_BUFFER|FD_PTR }, { "Size", FD_LONG|FD_BUFSIZE }, { 0, 0 } };

static const struct MethodEntry clVectorPathMethods[] = {
   { -30, (APTR)VECTORPATH_AddCommand, "AddCommand", maAddCommand, sizeof(struct vpAddCommand) },
   { -31, (APTR)VECTORPATH_RemoveCommand, "RemoveCommand", maRemoveCommand, sizeof(struct vpRemoveCommand) },
   { -32, (APTR)VECTORPATH_SetCommand, "SetCommand", maSetCommand, sizeof(struct vpSetCommand) },
   { -33, (APTR)VECTORPATH_GetCommand, "GetCommand", maGetCommand, sizeof(struct vpGetCommand) },
   { -34, (APTR)VECTORPATH_SetCommandList, "SetCommandList", maSetCommandList, sizeof(struct vpSetCommandList) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clVectorPathActions[] = {
   { AC_Clear, VECTORPATH_Clear },
   { AC_Flush, VECTORPATH_Flush },
   { AC_Free, VECTORPATH_Free },
   { AC_Init, VECTORPATH_Init },
   { AC_NewObject, VECTORPATH_NewObject },
   { 0, NULL }
};

