// Auto-generated by idl-c.fluid

FDEF maAddCommand[] = { { "PathCommand:Commands", FD_BUFFER|FD_PTR|FD_STRUCT }, { "Size", FD_INT|FD_BUFSIZE }, { 0, 0 } };
FDEF maRemoveCommand[] = { { "Index", FD_INT }, { "Total", FD_INT }, { 0, 0 } };
FDEF maSetCommand[] = { { "Index", FD_INT }, { "PathCommand:Command", FD_BUFFER|FD_PTR|FD_STRUCT }, { "Size", FD_INT|FD_BUFSIZE }, { 0, 0 } };
FDEF maGetCommand[] = { { "Index", FD_INT }, { "PathCommand:Command", FD_PTR|FD_STRUCT|FD_RESULT }, { 0, 0 } };
FDEF maSetCommandList[] = { { "Commands", FD_BUFFER|FD_PTR }, { "Size", FD_INT|FD_BUFSIZE }, { 0, 0 } };

static const struct MethodEntry clVectorPathMethods[] = {
   { AC(-30), (APTR)VECTORPATH_AddCommand, "AddCommand", maAddCommand, sizeof(struct vp::AddCommand) },
   { AC(-31), (APTR)VECTORPATH_RemoveCommand, "RemoveCommand", maRemoveCommand, sizeof(struct vp::RemoveCommand) },
   { AC(-32), (APTR)VECTORPATH_SetCommand, "SetCommand", maSetCommand, sizeof(struct vp::SetCommand) },
   { AC(-33), (APTR)VECTORPATH_GetCommand, "GetCommand", maGetCommand, sizeof(struct vp::GetCommand) },
   { AC(-34), (APTR)VECTORPATH_SetCommandList, "SetCommandList", maSetCommandList, sizeof(struct vp::SetCommandList) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clVectorPathActions[] = {
   { AC::Clear, VECTORPATH_Clear },
   { AC::Flush, VECTORPATH_Flush },
   { AC::Free, VECTORPATH_Free },
   { AC::Init, VECTORPATH_Init },
   { AC::NewObject, VECTORPATH_NewObject },
   { AC::NIL, NULL }
};

