// Auto-generated by idl-c.fluid

static const struct ActionArray clVectorViewportActions[] = {
   { AC_Clear, (APTR)VECTORVIEWPORT_Clear },
   { AC_Free, (APTR)VECTORVIEWPORT_Free },
   { AC_Init, (APTR)VECTORVIEWPORT_Init },
   { AC_Move, (APTR)VECTORVIEWPORT_Move },
   { AC_MoveToPoint, (APTR)VECTORVIEWPORT_MoveToPoint },
   { AC_NewObject, (APTR)VECTORVIEWPORT_NewObject },
   { AC_Resize, (APTR)VECTORVIEWPORT_Resize },
   { 0, 0 }
};

