// Auto-generated by idl-c.fluid

static const struct ActionArray clVectorViewportActions[] = {
   { AC_Clear, VECTORVIEWPORT_Clear },
   { AC_Free, VECTORVIEWPORT_Free },
   { AC_Init, VECTORVIEWPORT_Init },
   { AC_Move, VECTORVIEWPORT_Move },
   { AC_MoveToPoint, VECTORVIEWPORT_MoveToPoint },
   { AC_NewObject, VECTORVIEWPORT_NewObject },
   { AC_Redimension, VECTORVIEWPORT_Redimension },
   { AC_Resize, VECTORVIEWPORT_Resize },
   { 0, NULL }
};

