// Auto-generated by idl-c.fluid

static const struct FieldDef clFontFlags[] = {
   { "Antialias", 0x00000004 },
   { "Scalable", 0x10000000 },
   { "Bold", 0x20000000 },
   { "Kerning", 0x80000000 },
   { "Italic", 0x40000000 },
   { "AllowScale", 0x00000080 },
   { "HeavyLine", 0x00000008 },
   { "QuickAlias", 0x00000010 },
   { "BaseLine", 0x00000040 },
   { "PreferScaled", 0x00000001 },
   { "PreferFixed", 0x00000002 },
   { "CharClip", 0x00000020 },
   { "Smooth", 0x00000004 },
   { NULL, 0 }
};

static const struct FieldDef clFontAlign[] = {
   { "Bottom", 0x00000020 },
   { "Left", 0x00000001 },
   { "Horizontal", 0x00000004 },
   { "Top", 0x00000010 },
   { "Middle", 0x0000000c },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Right", 0x00000002 },
   { NULL, 0 }
};

static const struct ActionArray clFontActions[] = {
   { AC_Draw, (APTR)FONT_Draw },
   { AC_Free, (APTR)FONT_Free },
   { AC_Init, (APTR)FONT_Init },
   { AC_NewObject, (APTR)FONT_NewObject },
   { 0, 0 }
};

