# Build pipeline configuration for Travis CI

language: cpp
dist: xenial
compiler:
- gcc

os:
- linux

before_install:
- sudo apt-get update
- sudo apt-get install -y rsync libasound2-dev libxrandr-dev libxxf86dga-dev

script:
- make 3rdparty
- make full-compile

after_success:
- make install

branches:
  only:
  - master
