# Build pipeline configuration for Travis CI

language: cpp
compiler:
- gcc

os:
- linux
- windows

jobs:
  include:
    - os: linux
      dist: xenial
    - os: windows

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        export # Print all environment variables for help debugging
        gcc -dM -E - < /dev/null # Print all GCC predefined constants to aid debugging
        ;;
      linux)
        sudo apt-get update
        sudo apt-get install -y rsync libasound2-dev libxrandr-dev libxxf86dga-dev
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

script:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $mingw64 cmake -S . -B release -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        $mingw64 cmake --build release -j 8 -- -O
        $mingw64 cmake cd release && ctest
        ;;
      linux)
        cmake -S . -B release -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build release -j 8 -- -O
        cmake cd release && ctest
        ;;
    esac

after_success:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        cmake --install release
        ;;
      linux)
        cmake --install release
        ;;
    esac

branches:
  only:
  - master
  - /test\/.*/
  - /release\/.*/

