// Auto-generated by idl-c.fluid

static const struct FieldDef clFontFlags[] = {
   { "HeavyLine", 0x00000001 },
   { "BaseLine", 0x00000002 },
   { "Bold", 0x20000000 },
   { "Italic", 0x40000000 },
   { nullptr, 0 }
};

static const struct FieldDef clFontAlign[] = {
   { "Left", 0x00000001 },
   { "Right", 0x00000002 },
   { "Horizontal", 0x00000004 },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Middle", 0x0000000c },
   { "Top", 0x00000010 },
   { "Bottom", 0x00000020 },
   { nullptr, 0 }
};

static const struct FieldDef clFontALIGN[] = {
   { "Left", 0x00000001 },
   { "Right", 0x00000002 },
   { "Horizontal", 0x00000004 },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Middle", 0x0000000c },
   { "Top", 0x00000010 },
   { "Bottom", 0x00000020 },
   { nullptr, 0 }
};

static const struct ActionArray clFontActions[] = {
   { AC::Draw, FONT_Draw },
   { AC::Free, FONT_Free },
   { AC::Init, FONT_Init },
   { AC::NewPlacement, FONT_NewPlacement },
   { AC::NIL, nullptr }
};

