// Auto-generated by idl-c.fluid

static const struct FieldDef clFontFlags[] = {
   { "RequireScaled", 0x00000001 },
   { "RequireFixed", 0x00000002 },
   { "HeavyLine", 0x00000004 },
   { "BaseLine", 0x00000008 },
   { "Variable", 0x08000000 },
   { "Scalable", 0x10000000 },
   { "Bold", 0x20000000 },
   { "Italic", 0x40000000 },
   { "Kerning", (LONG)0x80000000 },
   { NULL, 0 }
};

static const struct FieldDef clFontAlign[] = {
   { "Left", 0x00000001 },
   { "Right", 0x00000002 },
   { "Horizontal", 0x00000004 },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Middle", 0x0000000c },
   { "Top", 0x00000010 },
   { "Bottom", 0x00000020 },
   { NULL, 0 }
};

static const struct ActionArray clFontActions[] = {
   { AC_Draw, FONT_Draw },
   { AC_Free, FONT_Free },
   { AC_Init, FONT_Init },
   { AC_NewObject, FONT_NewObject },
   { 0, NULL }
};

