// Auto-generated by idl-c.fluid

namespace fnt {
extern ERR GetList(struct FontList ** Result);
extern int StringWidth(objFont * Font, CSTRING String, int Chars);
extern int CharWidth(objFont * Font, uint32_t Char);
extern ERR RefreshFonts();
extern ERR SelectFont(CSTRING Name, CSTRING Style, CSTRING * Path, FMETA * Meta);
extern ERR ResolveFamilyName(CSTRING String, CSTRING * Result);

} // namespace
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsCharWidth[] = { { "Result", FD_LONG }, { "Font", FD_OBJECTPTR }, { "Char", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF argsGetList[] = { { "Error", FD_LONG|FD_ERROR }, { "FontList:Result", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF argsRefreshFonts[] = { { "Error", FD_LONG|FD_ERROR }, { 0, 0 } };
FDEF argsResolveFamilyName[] = { { "Error", FD_LONG|FD_ERROR }, { "String", FD_STR }, { "Result", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF argsSelectFont[] = { { "Error", FD_LONG|FD_ERROR }, { "Name", FD_STR }, { "Style", FD_STR }, { "Path", FD_STR|FD_ALLOC|FD_RESULT }, { "Meta", FD_LONG|FD_RESULT }, { 0, 0 } };
FDEF argsStringWidth[] = { { "Result", FD_LONG }, { "Font", FD_OBJECTPTR }, { "String", FD_STR }, { "Chars", FD_LONG }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)fnt::GetList, "GetList", argsGetList },
   { (APTR)fnt::StringWidth, "StringWidth", argsStringWidth },
   { (APTR)fnt::CharWidth, "CharWidth", argsCharWidth },
   { (APTR)fnt::RefreshFonts, "RefreshFonts", argsRefreshFonts },
   { (APTR)fnt::SelectFont, "SelectFont", argsSelectFont },
   { (APTR)fnt::ResolveFamilyName, "ResolveFamilyName", argsResolveFamilyName },
   { NULL, NULL, NULL }
};

#undef MOD_IDL
#define MOD_IDL "s.FontList:pNext:FontList,sName,sAlias,lPoints[0],sStyles,sAxes,cScalable,cVariable,cHinting,cHidden\nc.FMETA:HIDDEN=0x20,HINT_INTERNAL=0x10,HINT_LIGHT=0x8,HINT_NORMAL=0x4,SCALED=0x1,VARIABLE=0x2\nc.FSS:ALL=0xffffffff,LINE=0xfffffffe\nc.FTF:BASE_LINE=0x2,BOLD=0x20000000,HEAVY_LINE=0x1,ITALIC=0x40000000\nc.HINT:INTERNAL=0x2,LIGHT=0x3,NORMAL=0x1\n"
