// Auto-generated by idl-c.fluid

static const struct FieldDef clXQueryXQF[] = {
   { "Xpath", 0x00000001 },
   { "HasProlog", 0x00000002 },
   { "LibraryModule", 0x00000004 },
   { "ModuleImports", 0x00000008 },
   { "DefaultFunctionNs", 0x00000010 },
   { "DefaultElementNs", 0x00000020 },
   { "BaseUriDeclared", 0x00000040 },
   { "DefaultCollationDeclared", 0x00000080 },
   { "BoundaryPreserve", 0x00000100 },
   { "ConstructionPreserve", 0x00000200 },
   { "OrderingUnordered", 0x00000400 },
   { "HasWildcardTests", 0x00000800 },
   { nullptr, 0 }
};

FDEF maEvaluate[] = { { "XML", FD_OBJECTPTR }, { 0, 0 } };
FDEF maSearch[] = { { "XML", FD_OBJECTPTR }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maRegisterFunction[] = { { "FunctionName", FD_STR }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maInspectFunctions[] = { { "Name", FD_STR }, { "ResultFlags", FD_INT }, { "Result", FD_PTR }, { 0, 0 } };

static const struct MethodEntry clXQueryMethods[] = {
   { AC(-1), (APTR)XQUERY_Evaluate, "Evaluate", maEvaluate, sizeof(struct xq::Evaluate) },
   { AC(-2), (APTR)XQUERY_Search, "Search", maSearch, sizeof(struct xq::Search) },
   { AC(-3), (APTR)XQUERY_RegisterFunction, "RegisterFunction", maRegisterFunction, sizeof(struct xq::RegisterFunction) },
   { AC(-4), (APTR)XQUERY_InspectFunctions, "InspectFunctions", maInspectFunctions, sizeof(struct xq::InspectFunctions) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clXQueryActions[] = {
   { AC::Activate, XQUERY_Activate },
   { AC::Clear, XQUERY_Clear },
   { AC::Free, XQUERY_Free },
   { AC::GetKey, XQUERY_GetKey },
   { AC::Init, XQUERY_Init },
   { AC::NewPlacement, XQUERY_NewPlacement },
   { AC::Reset, XQUERY_Reset },
   { AC::SetKey, XQUERY_SetKey },
   { AC::NIL, nullptr }
};

