// Auto-generated by idl-c.fluid

static const struct FieldDef clBitmapType[] = {
   { "Planar", 0x00000002 },
   { "Chunky", 0x00000003 },
   { NULL, 0 }
};

static const struct FieldDef clBitmapFlags[] = {
   { "BlankPalette", 0x00000001 },
   { "Queried", 0x00000040 },
   { "NeverShrink", 0x00001000 },
   { "Compressed", 0x00000002 },
   { "Clear", 0x00000080 },
   { "X11DGA", 0x00002000 },
   { "NoData", 0x00000004 },
   { "Transparent", 0x00000008 },
   { "FixedDepth", 0x00004000 },
   { "Accelerated2D", 0x00000200 },
   { "NoBlend", 0x00008000 },
   { "Mask", 0x00000010 },
   { "Accelerated3D", 0x00000400 },
   { "User", 0x00000100 },
   { "InverseAlpha", 0x00000020 },
   { "AlphaChannel", 0x00000800 },
   { NULL, 0 }
};

FDEF maCopyArea[] = { { "DestBitmap", FD_OBJECTPTR }, { "Flags", FD_LONG }, { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { "XDest", FD_LONG }, { "YDest", FD_LONG }, { 0, 0 } };
FDEF maCompress[] = { { "Level", FD_LONG }, { 0, 0 } };
FDEF maDecompress[] = { { "RetainData", FD_LONG }, { 0, 0 } };
FDEF maFlip[] = { { "Orientation", FD_LONG }, { 0, 0 } };
FDEF maFlood[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "Colour", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF maDrawRectangle[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { "Colour", FD_LONG|FD_UNSIGNED }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maSetClipRegion[] = { { "Number", FD_LONG }, { "Left", FD_LONG }, { "Top", FD_LONG }, { "Right", FD_LONG }, { "Bottom", FD_LONG }, { "Terminate", FD_LONG }, { 0, 0 } };
FDEF maGetColour[] = { { "Red", FD_LONG }, { "Green", FD_LONG }, { "Blue", FD_LONG }, { "Alpha", FD_LONG }, { "Colour", FD_LONG|FD_UNSIGNED|FD_RESULT }, { 0, 0 } };
FDEF maDrawLine[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "XEnd", FD_LONG }, { "YEnd", FD_LONG }, { "Colour", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF maCopyStretch[] = { { "DestBitmap", FD_OBJECTPTR }, { "Flags", FD_LONG }, { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { "XDest", FD_LONG }, { "YDest", FD_LONG }, { "DestWidth", FD_LONG }, { "DestHeight", FD_LONG }, { 0, 0 } };

static const struct MethodArray clBitmapMethods[] = {
   { -1, (APTR)BITMAP_CopyArea, "CopyArea", maCopyArea, sizeof(struct bmpCopyArea) },
   { -2, (APTR)BITMAP_Compress, "Compress", maCompress, sizeof(struct bmpCompress) },
   { -3, (APTR)BITMAP_Decompress, "Decompress", maDecompress, sizeof(struct bmpDecompress) },
   { -4, (APTR)BITMAP_Flip, "Flip", maFlip, sizeof(struct bmpFlip) },
   { -5, (APTR)BITMAP_Flood, "Flood", maFlood, sizeof(struct bmpFlood) },
   { -6, (APTR)BITMAP_DrawRectangle, "DrawRectangle", maDrawRectangle, sizeof(struct bmpDrawRectangle) },
   { -7, (APTR)BITMAP_SetClipRegion, "SetClipRegion", maSetClipRegion, sizeof(struct bmpSetClipRegion) },
   { -8, (APTR)BITMAP_GetColour, "GetColour", maGetColour, sizeof(struct bmpGetColour) },
   { -9, (APTR)BITMAP_DrawLine, "DrawLine", maDrawLine, sizeof(struct bmpDrawLine) },
   { -10, (APTR)BITMAP_CopyStretch, "CopyStretch", maCopyStretch, sizeof(struct bmpCopyStretch) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clBitmapActions[] = {
   { AC_AccessObject, (APTR)BITMAP_AccessObject },
   { AC_Clear, (APTR)BITMAP_Clear },
   { AC_CopyData, (APTR)BITMAP_CopyData },
   { AC_Draw, (APTR)BITMAP_Draw },
   { AC_Flush, (APTR)BITMAP_Flush },
   { AC_Free, (APTR)BITMAP_Free },
   { AC_Init, (APTR)BITMAP_Init },
   { AC_Lock, (APTR)BITMAP_Lock },
   { AC_NewObject, (APTR)BITMAP_NewObject },
   { AC_Query, (APTR)BITMAP_Query },
   { AC_Read, (APTR)BITMAP_Read },
   { AC_ReleaseObject, (APTR)BITMAP_ReleaseObject },
   { AC_Resize, (APTR)BITMAP_Resize },
   { AC_SaveImage, (APTR)BITMAP_SaveImage },
   { AC_Seek, (APTR)BITMAP_Seek },
   { AC_Unlock, (APTR)BITMAP_Unlock },
   { AC_Write, (APTR)BITMAP_Write },
   { 0, 0 }
};

