// Auto-generated by idl-c.fluid

static const struct FieldDef clControllerButtons[] = {
   { "GamepadS", 0x00000001 },
   { "GamepadE", 0x00000002 },
   { "GamepadW", 0x00000004 },
   { "GamepadN", 0x00000008 },
   { "DpadUp", 0x00000010 },
   { "DpadDown", 0x00000020 },
   { "DpadLeft", 0x00000040 },
   { "DpadRight", 0x00000080 },
   { "Start", 0x00000100 },
   { "Select", 0x00000200 },
   { "LeftBumper1", 0x00000400 },
   { "LeftBumper2", 0x00000800 },
   { "RightBumper1", 0x00001000 },
   { "RightBumper2", 0x00002000 },
   { "LeftThumb", 0x00004000 },
   { "RightThumb", 0x00008000 },
   { nullptr, 0 }
};

static const struct ActionArray clControllerActions[] = {
   { AC::Query, CONTROLLER_Query },
   { AC::NIL, nullptr }
};

