// Auto-generated by idl-c.fluid

static const struct FieldDef clClipboardFlags[] = {
   { "DragDrop", 0x00000001 },
   { "Host", 0x00000002 },
   { "HistoryBuffer", 0x00000004 },
   { NULL, 0 }
};

FDEF maAddFile[] = { { "Datatype", FD_LONG }, { "Path", FD_STR }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maAddObjects[] = { { "Datatype", FD_LONG }, { "Objects", FD_PTR }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maGetFiles[] = { { "Filter", FD_LONG }, { "Index", FD_LONG }, { "Datatype", FD_LONG|FD_RESULT }, { "Files", FD_ARRAY|FD_STR|FD_ALLOC|FD_RESULT }, { "Flags", FD_LONG|FD_RESULT }, { 0, 0 } };
FDEF maAddText[] = { { "String", FD_STR }, { 0, 0 } };
FDEF maRemove[] = { { "Datatype", FD_LONG }, { 0, 0 } };

static const struct MethodEntry clClipboardMethods[] = {
   { AC(-1), (APTR)CLIPBOARD_AddFile, "AddFile", maAddFile, sizeof(struct clip::AddFile) },
   { AC(-2), (APTR)CLIPBOARD_AddObjects, "AddObjects", maAddObjects, sizeof(struct clip::AddObjects) },
   { AC(-3), (APTR)CLIPBOARD_GetFiles, "GetFiles", maGetFiles, sizeof(struct clip::GetFiles) },
   { AC(-4), (APTR)CLIPBOARD_AddText, "AddText", maAddText, sizeof(struct clip::AddText) },
   { AC(-5), (APTR)CLIPBOARD_Remove, "Remove", maRemove, sizeof(struct clip::Remove) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clClipboardActions[] = {
   { AC::Clear, CLIPBOARD_Clear },
   { AC::DataFeed, CLIPBOARD_DataFeed },
   { AC::Free, CLIPBOARD_Free },
   { AC::Init, CLIPBOARD_Init },
   { AC::NewObject, CLIPBOARD_NewObject },
   { AC::NIL, NULL }
};

