// Auto-generated by idl-c.fluid

#ifdef  __cplusplus
extern "C" {
#endif

ERROR gfxGetDisplayInfo(OBJECTID Display, struct DisplayInfoV3 ** Info);
LONG gfxGetDisplayType();
ERROR gfxSetCursor(OBJECTID Surface, LONG Flags, LONG Cursor, CSTRING Name, OBJECTID Owner);
ERROR gfxRestoreCursor(LONG Cursor, OBJECTID Owner);
ERROR gfxGetCursorPos(DOUBLE * X, DOUBLE * Y);
ERROR gfxSetCursorPos(DOUBLE X, DOUBLE Y);
ERROR gfxGetRelativeCursorPos(OBJECTID Surface, DOUBLE * X, DOUBLE * Y);
ERROR gfxGetCursorInfo(struct CursorInfo * Info, LONG Size);
ERROR gfxSetCustomCursor(OBJECTID Surface, LONG Flags, struct rkBitmap * Bitmap, LONG HotX, LONG HotY, OBJECTID Owner);
struct rkPointer * gfxAccessPointer();
ERROR gfxScanDisplayModes(CSTRING Filter, struct DisplayInfoV3 * Info, LONG Size);
ERROR gfxLockCursor(OBJECTID Surface);
ERROR gfxUnlockCursor(OBJECTID Surface);
ERROR gfxSetHostOption(LONG Option, LARGE Value);
ERROR gfxStartCursorDrag(OBJECTID Source, LONG Item, CSTRING Datatypes, OBJECTID Surface);
ERROR gfxCopySurface(struct BitmapSurfaceV2 * Surface, struct rkBitmap * Bitmap, LONG Flags, LONG X, LONG Y, LONG Width, LONG Height, LONG XDest, LONG YDest);
void gfxSync(struct rkBitmap * Bitmap);
ERROR gfxResample(struct rkBitmap * Bitmap, struct ColourFormat * ColourFormat);
void gfxGetColourFormat(struct ColourFormat * Format, LONG BitsPerPixel, LONG RedMask, LONG GreenMask, LONG BlueMask, LONG AlphaMask);
ERROR gfxCopyArea(struct rkBitmap * Bitmap, struct rkBitmap * Dest, LONG Flags, LONG X, LONG Y, LONG Width, LONG Height, LONG XDest, LONG YDest);
void gfxReadRGBPixel(struct rkBitmap * Bitmap, LONG X, LONG Y, struct RGB8 ** RGB);
ULONG gfxReadPixel(struct rkBitmap * Bitmap, LONG X, LONG Y);
void gfxDrawRGBPixel(struct rkBitmap * Bitmap, LONG X, LONG Y, struct RGB8 * RGB);
void gfxDrawPixel(struct rkBitmap * Bitmap, LONG X, LONG Y, ULONG Colour);
void gfxDrawLine(struct rkBitmap * Bitmap, LONG X, LONG Y, LONG XEnd, LONG YEnd, ULONG Colour);
void gfxDrawRectangle(struct rkBitmap * Bitmap, LONG X, LONG Y, LONG Width, LONG Height, ULONG Colour, LONG Flags);
void gfxFlipBitmap(struct rkBitmap * Bitmap, LONG Orientation);
void gfxSetClipRegion(struct rkBitmap * Bitmap, LONG Number, LONG Left, LONG Top, LONG Right, LONG Bottom, LONG Terminate);
ERROR gfxCompress(struct rkBitmap * Bitmap, LONG Level);
ERROR gfxDecompress(struct rkBitmap * Bitmap, LONG RetainData);
ERROR gfxSubscribeInput(FUNCTION * Callback, OBJECTID SurfaceFilter, LONG Mask, OBJECTID DeviceFilter, LONG * Handle);
ERROR gfxUnsubscribeInput(LONG Handle);
CSTRING gfxGetInputTypeName(LONG Type);
DOUBLE gfxScaleToDPI(DOUBLE Value);

#ifdef  __cplusplus
}
#endif
