// Auto-generated by idl-c.fluid

static const struct FieldDef clDocumentEventMask[] = {
   { "Path", 0x00000001 },
   { "OnClick", 0x00000002 },
   { "OnMotion", 0x00000004 },
   { "OnCrossingIn", 0x00000008 },
   { "OnCrossingOut", 0x00000010 },
   { "OnCrossing", 0x00000018 },
   { "LinkActivated", 0x00000020 },
   { NULL, 0 }
};

static const struct FieldDef clDocumentFlags[] = {
   { "Edit", 0x00000001 },
   { "Overwrite", 0x00000002 },
   { "NoSysKeys", 0x00000004 },
   { "Disabled", 0x00000008 },
   { "NoLayoutMsg", 0x00000010 },
   { "Unrestricted", 0x00000020 },
   { NULL, 0 }
};

FDEF maFeedParser[] = { { "String", FD_STR }, { 0, 0 } };
FDEF maSelectLink[] = { { "Index", FD_LONG }, { "Name", FD_STR }, { 0, 0 } };
FDEF maFindIndex[] = { { "Name", FD_STR }, { "Start", FD_LONG|FD_RESULT }, { "End", FD_LONG|FD_RESULT }, { 0, 0 } };
FDEF maInsertXML[] = { { "XML", FD_STR }, { "Index", FD_LONG }, { 0, 0 } };
FDEF maRemoveContent[] = { { "Start", FD_LONG }, { "End", FD_LONG }, { 0, 0 } };
FDEF maInsertText[] = { { "Text", FD_STR }, { "Index", FD_LONG }, { "Char", FD_LONG }, { "Preformat", FD_LONG }, { 0, 0 } };
FDEF maCallFunction[] = { { "Function", FD_STR }, { "ScriptArg:Args", FD_PTR|FD_STRUCT }, { "TotalArgs", FD_LONG }, { 0, 0 } };
FDEF maAddListener[] = { { "Trigger", FD_LONG }, { "Function", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maRemoveListener[] = { { "Trigger", FD_LONG }, { "Function", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maShowIndex[] = { { "Name", FD_STR }, { 0, 0 } };
FDEF maHideIndex[] = { { "Name", FD_STR }, { 0, 0 } };
FDEF maEdit[] = { { "Name", FD_STR }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maReadContent[] = { { "Format", FD_LONG }, { "Start", FD_LONG }, { "End", FD_LONG }, { "Result", FD_STR|FD_ALLOC|FD_RESULT }, { 0, 0 } };

static const struct MethodEntry clDocumentMethods[] = {
   { -1, (APTR)DOCUMENT_FeedParser, "FeedParser", maFeedParser, sizeof(struct docFeedParser) },
   { -2, (APTR)DOCUMENT_SelectLink, "SelectLink", maSelectLink, sizeof(struct docSelectLink) },
   { -4, (APTR)DOCUMENT_FindIndex, "FindIndex", maFindIndex, sizeof(struct docFindIndex) },
   { -5, (APTR)DOCUMENT_InsertXML, "InsertXML", maInsertXML, sizeof(struct docInsertXML) },
   { -6, (APTR)DOCUMENT_RemoveContent, "RemoveContent", maRemoveContent, sizeof(struct docRemoveContent) },
   { -7, (APTR)DOCUMENT_InsertText, "InsertText", maInsertText, sizeof(struct docInsertText) },
   { -8, (APTR)DOCUMENT_CallFunction, "CallFunction", maCallFunction, sizeof(struct docCallFunction) },
   { -9, (APTR)DOCUMENT_AddListener, "AddListener", maAddListener, sizeof(struct docAddListener) },
   { -10, (APTR)DOCUMENT_RemoveListener, "RemoveListener", maRemoveListener, sizeof(struct docRemoveListener) },
   { -11, (APTR)DOCUMENT_ShowIndex, "ShowIndex", maShowIndex, sizeof(struct docShowIndex) },
   { -12, (APTR)DOCUMENT_HideIndex, "HideIndex", maHideIndex, sizeof(struct docHideIndex) },
   { -13, (APTR)DOCUMENT_Edit, "Edit", maEdit, sizeof(struct docEdit) },
   { -14, (APTR)DOCUMENT_ReadContent, "ReadContent", maReadContent, sizeof(struct docReadContent) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clDocumentActions[] = {
   { AC_Activate, DOCUMENT_Activate },
   { AC_Clear, DOCUMENT_Clear },
   { AC_Clipboard, DOCUMENT_Clipboard },
   { AC_DataFeed, DOCUMENT_DataFeed },
   { AC_Disable, DOCUMENT_Disable },
   { AC_Draw, DOCUMENT_Draw },
   { AC_Enable, DOCUMENT_Enable },
   { AC_Focus, DOCUMENT_Focus },
   { AC_Free, DOCUMENT_Free },
   { AC_GetKey, DOCUMENT_GetKey },
   { AC_Init, DOCUMENT_Init },
   { AC_NewObject, DOCUMENT_NewObject },
   { AC_Refresh, DOCUMENT_Refresh },
   { AC_SaveToObject, DOCUMENT_SaveToObject },
   { AC_ScrollToPoint, DOCUMENT_ScrollToPoint },
   { AC_SetKey, DOCUMENT_SetKey },
   { 0, NULL }
};

