// Auto-generated by idl-c.fluid

static ERROR sndStartDrivers();
static ERROR sndWaitDrivers(LONG TimeOut);
static LONG sndSetChannels(LONG Total);
static DOUBLE sndSetTaskVolume(DOUBLE Volume);

#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsSetChannels[] = { { "Result", FD_LONG }, { "Total", FD_LONG }, { 0, 0 } };
FDEF argsSetTaskVolume[] = { { "Result", FD_DOUBLE }, { "Volume", FD_DOUBLE }, { 0, 0 } };
FDEF argsStartDrivers[] = { { "Error", FD_LONG|FD_ERROR }, { 0, 0 } };
FDEF argsWaitDrivers[] = { { "Error", FD_LONG|FD_ERROR }, { "TimeOut", FD_LONG }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)sndStartDrivers, "StartDrivers", argsStartDrivers },
   { (APTR)sndWaitDrivers, "WaitDrivers", argsWaitDrivers },
   { (APTR)sndSetChannels, "SetChannels", argsSetChannels },
   { (APTR)sndSetTaskVolume, "SetTaskVolume", argsSetTaskVolume },
   { NULL, NULL, NULL }
};

#undef MOD_IDL
#define MOD_IDL "s.AudioSample:pData,lStreamID,lSampleLength,lLoop1Start,lLoop1End,lLoop2Start,lLoop2End,lSeekStart,lStreamLength,lBufferLength,lStreamPos,ucSampleType,cLoopMode,cLoop1Type,cLoop2Type,cUsed,cFree\ns.AudioChannel:eSample:AudioSample,lSoundID,lSampleHandle,lFlags,ulPosition,ulFrequency,uwPositionLow,wLVolume,wRVolume,wLVolumeTarget,wRVolumeTarget,wVolume,cPriority,cState[CHS],cLoopIndex,cPan\ns.AudioCommand:lCommandID,lHandle,lData\ns.ChannelSet:pChannel:AudioChannel,pCommands:AudioCommand,lUpdateRate,lMixLeft,lKey,lTaskID,lChannelMID,lCommandMID,dTaskVolume,wTotal,wActual,wTotalCommands,wPosition,wOpenCount\ns.VolumeCtl:wSize,ucName[32],lFlags,fChannels[1]\ns.AudioLoop:wLoopMode,cLoop1Type[LTYPE],cLoop2Type[LTYPE],lLoop1Start,lLoop1End,lLoop2Start,lLoop2End\nc.VCF:SYNC=0x100000,JOINED=0x100,PLAYBACK=0x1,MUTE=0x10000,CAPTURE=0x10,MONO=0x1000\nc.SVF:SYNC=0x100000,CAPTURE=0x10000,MUTE=0x100,UNMUTE=0x1000,UNSYNC=0x1000000\nc.ADF:STEREO=0x8,OVER_SAMPLING=0x1,SERVICE_MODE=0x80,SYSTEM_WIDE=0x40,FILTER_LOW=0x2,FILTER_HIGH=0x4,VOL_RAMPING=0x10,AUTO_SAVE=0x20\nc.SDF:STEREO=0x8,NOTE=0x80000000,NEW=0x2,STREAM=0x40000000,RESTRICT_PLAY=0x20,TERMINATE=0x10,QUERY=0x4,LOOP=0x1\nc.CHS:FINISHED=0x1,PLAYING=0x2,FADE_OUT=0x4,STOPPED=0x0,RELEASED=0x3\nc.STREAM:SMART=0x2,ALWAYS=0x3,NEVER=0x1\nc.NOTE:B=0xb,D=0x2,FS=0x6,A=0x9,E=0x4,GS=0x8,F=0x5,OCTAVE=0xc,AS=0xa,DS=0x3,CS=0x1,C=0x0,G=0x7\nc.LTYPE:BIDIRECTIONAL=0x2,UNIDIRECTIONAL=0x1\nc.SFM:S16_BIT_MONO=0x2,U8_BIT_STEREO=0x3,U8_BIT_MONO=0x1,BIG_ENDIAN=0x80000000,END=0x5,S16_BIT_STEREO=0x4\nc.CHF:BACKWARD=0x2,CHANGED=0x8,VOL_RAMP=0x4,MUTE=0x1\nc.CMD:SET_PAN=0x4,CONTINUE=0xf,SET_LENGTH=0xe,STOP=0x7,FADE_OUT=0xc,FADE_IN=0xb,SET_VOLUME=0x3,SET_SAMPLE=0x2,PLAY=0xa,END_SEQUENCE=0x1,SET_POSITION=0x9,MUTE=0xd,SET_RATE=0x6,SET_FREQUENCY=0x5,START_SEQUENCE=0x0,STOP_LOOPING=0x8\nc.LOOP:SINGLE_RELEASE=0x2,DOUBLE=0x3,AMIGA=0x5,SINGLE=0x1,AMIGA_NONE=0x4\n"
