// Auto-generated by idl-c.fluid

static const struct FieldDef clXMLFlags[] = {
   { "WellFormed", 0x00000001 },
   { "IncludeComments", 0x00000002 },
   { "StripContent", 0x00000004 },
   { "Indent", 0x00000008 },
   { "Readable", 0x00000008 },
   { "LockRemove", 0x00000010 },
   { "StripHeaders", 0x00000020 },
   { "New", 0x00000040 },
   { "NoEscape", 0x00000080 },
   { "IncludeWhitespace", 0x00000100 },
   { "ParseHTML", 0x00000200 },
   { "StripCDATA", 0x00000400 },
   { "LogAll", 0x00000800 },
   { "ParseEntity", 0x00001000 },
   { "OmitTags", 0x00002000 },
   { "NamespaceAware", 0x00004000 },
   { "HasSchema", 0x00008000 },
   { "Standalone", 0x00010000 },
   { "IncludeSiblings", (int)0x80000000 },
   { nullptr, 0 }
};

FDEF maSetAttrib[] = { { "Index", FD_INT }, { "Attrib", FD_INT }, { "Name", FD_STR }, { "Value", FD_STR }, { 0, 0 } };
FDEF maSerialise[] = { { "Index", FD_INT }, { "Flags", FD_INT }, { "Result", FD_STR|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF maInsertXML[] = { { "Index", FD_INT }, { "Where", FD_INT }, { "XML", FD_STR }, { "Result", FD_INT|FD_RESULT }, { 0, 0 } };
FDEF maGetContent[] = { { "Index", FD_INT }, { "Buffer", FD_BUFFER|FD_STR }, { "Length", FD_INT|FD_BUFSIZE }, { 0, 0 } };
FDEF maSort[] = { { "XPath", FD_STR }, { "Sort", FD_STR }, { "Flags", FD_INT }, { 0, 0 } };
FDEF maRemoveTag[] = { { "Index", FD_INT }, { "Total", FD_INT }, { 0, 0 } };
FDEF maMoveTags[] = { { "Index", FD_INT }, { "Total", FD_INT }, { "DestIndex", FD_INT }, { "Where", FD_INT }, { 0, 0 } };
FDEF maGetAttrib[] = { { "Index", FD_INT }, { "Attrib", FD_STR }, { "Value", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maInsertXPath[] = { { "XPath", FD_STR }, { "Where", FD_INT }, { "XML", FD_STR }, { "Result", FD_INT|FD_RESULT }, { 0, 0 } };
FDEF maFindTag[] = { { "XPath", FD_STR }, { "Callback", FD_FUNCTIONPTR }, { "Result", FD_INT|FD_RESULT }, { 0, 0 } };
FDEF maFilter[] = { { "XPath", FD_STR }, { 0, 0 } };
FDEF maCount[] = { { "XPath", FD_STR }, { "Result", FD_INT|FD_RESULT }, { 0, 0 } };
FDEF maInsertContent[] = { { "Index", FD_INT }, { "Where", FD_INT }, { "Content", FD_STR }, { "Result", FD_INT|FD_RESULT }, { 0, 0 } };
FDEF maRemoveXPath[] = { { "XPath", FD_STR }, { "Limit", FD_INT }, { 0, 0 } };
FDEF maGetTag[] = { { "Index", FD_INT }, { "XMLTag:Result", FD_PTR|FD_STRUCT|FD_RESULT }, { 0, 0 } };
FDEF maRegisterNamespace[] = { { "URI", FD_STR }, { "Result", FD_INT|FD_UNSIGNED|FD_RESULT }, { 0, 0 } };
FDEF maGetNamespaceURI[] = { { "NamespaceID", FD_INT|FD_UNSIGNED }, { "Result", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSetTagNamespace[] = { { "TagID", FD_INT }, { "NamespaceID", FD_INT }, { 0, 0 } };
FDEF maResolvePrefix[] = { { "Prefix", FD_STR }, { "TagID", FD_INT }, { "Result", FD_INT|FD_UNSIGNED|FD_RESULT }, { 0, 0 } };
FDEF maSetVariable[] = { { "Key", FD_STR }, { "Value", FD_STR }, { 0, 0 } };
FDEF maGetEntity[] = { { "Name", FD_STR }, { "Value", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maGetNotation[] = { { "Name", FD_STR }, { "Value", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maLoadSchema[] = { { "Path", FD_STR }, { 0, 0 } };

static const struct MethodEntry clXMLMethods[] = {
   { AC(-1), (APTR)XML_SetAttrib, "SetAttrib", maSetAttrib, sizeof(struct xml::SetAttrib) },
   { AC(-2), (APTR)XML_Serialise, "Serialise", maSerialise, sizeof(struct xml::Serialise) },
   { AC(-3), (APTR)XML_InsertXML, "InsertXML", maInsertXML, sizeof(struct xml::InsertXML) },
   { AC(-4), (APTR)XML_GetContent, "GetContent", maGetContent, sizeof(struct xml::GetContent) },
   { AC(-5), (APTR)XML_Sort, "Sort", maSort, sizeof(struct xml::Sort) },
   { AC(-6), (APTR)XML_RemoveTag, "RemoveTag", maRemoveTag, sizeof(struct xml::RemoveTag) },
   { AC(-7), (APTR)XML_MoveTags, "MoveTags", maMoveTags, sizeof(struct xml::MoveTags) },
   { AC(-8), (APTR)XML_GetAttrib, "GetAttrib", maGetAttrib, sizeof(struct xml::GetAttrib) },
   { AC(-9), (APTR)XML_InsertXPath, "InsertXPath", maInsertXPath, sizeof(struct xml::InsertXPath) },
   { AC(-10), (APTR)XML_FindTag, "FindTag", maFindTag, sizeof(struct xml::FindTag) },
   { AC(-11), (APTR)XML_Filter, "Filter", maFilter, sizeof(struct xml::Filter) },
   { AC(-13), (APTR)XML_Count, "Count", maCount, sizeof(struct xml::Count) },
   { AC(-14), (APTR)XML_InsertContent, "InsertContent", maInsertContent, sizeof(struct xml::InsertContent) },
   { AC(-15), (APTR)XML_RemoveXPath, "RemoveXPath", maRemoveXPath, sizeof(struct xml::RemoveXPath) },
   { AC(-18), (APTR)XML_GetTag, "GetTag", maGetTag, sizeof(struct xml::GetTag) },
   { AC(-19), (APTR)XML_RegisterNamespace, "RegisterNamespace", maRegisterNamespace, sizeof(struct xml::RegisterNamespace) },
   { AC(-20), (APTR)XML_GetNamespaceURI, "GetNamespaceURI", maGetNamespaceURI, sizeof(struct xml::GetNamespaceURI) },
   { AC(-21), (APTR)XML_SetTagNamespace, "SetTagNamespace", maSetTagNamespace, sizeof(struct xml::SetTagNamespace) },
   { AC(-22), (APTR)XML_ResolvePrefix, "ResolvePrefix", maResolvePrefix, sizeof(struct xml::ResolvePrefix) },
   { AC(-23), (APTR)XML_SetVariable, "SetVariable", maSetVariable, sizeof(struct xml::SetVariable) },
   { AC(-24), (APTR)XML_GetEntity, "GetEntity", maGetEntity, sizeof(struct xml::GetEntity) },
   { AC(-25), (APTR)XML_GetNotation, "GetNotation", maGetNotation, sizeof(struct xml::GetNotation) },
   { AC(-26), (APTR)XML_LoadSchema, "LoadSchema", maLoadSchema, sizeof(struct xml::LoadSchema) },
   { AC(-27), (APTR)XML_ValidateDocument, "ValidateDocument", 0, 0 },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clXMLActions[] = {
   { AC::Clear, XML_Clear },
   { AC::DataFeed, XML_DataFeed },
   { AC::Free, XML_Free },
   { AC::GetKey, XML_GetKey },
   { AC::Init, XML_Init },
   { AC::NewPlacement, XML_NewPlacement },
   { AC::Reset, XML_Reset },
   { AC::SaveToObject, XML_SaveToObject },
   { AC::SetKey, XML_SetKey },
   { AC::NIL, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "s.XMLAttrib:zsName,zsValue\ns.XMLTag:lID,lParentID,lLineNo,lFlags,ulNamespaceID,zeAttribs:XMLAttrib[],zeChildren:XMLTag[]\nc.XMF:HAS_SCHEMA=0x8000,INCLUDE_COMMENTS=0x2,INCLUDE_SIBLINGS=0x80000000,INCLUDE_WHITESPACE=0x100,INDENT=0x8,LOCK_REMOVE=0x10,LOG_ALL=0x800,NAMESPACE_AWARE=0x4000,NEW=0x40,NO_ESCAPE=0x80,OMIT_TAGS=0x2000,PARSE_ENTITY=0x1000,PARSE_HTML=0x200,READABLE=0x8,STANDALONE=0x10000,STRIP_CDATA=0x400,STRIP_CONTENT=0x4,STRIP_HEADERS=0x20,WELL_FORMED=0x1\nc.XMI:CHILD=0x1,CHILD_END=0x3,END=0x4,NEXT=0x2,PREV=0x0,PREVIOUS=0x0\nc.XMS:NEW=0xffffffff,UPDATE=0xfffffffd,UPDATE_ONLY=0xfffffffe\nc.XSF:CHECK_SORT=0x2,DESC=0x1\nc.XTF:CDATA=0x1,COMMENT=0x8,INSTRUCTION=0x2,NOTATION=0x4\n"
