// Auto-generated by idl-c.fluid

static const struct FieldDef clViewFlags[] = {
   { "WidthReset", 0x00000020 },
   { "NoSorting", 0x00000008 },
   { "Sensitive", 0x00000004 },
   { "NoIcons", 0x00000002 },
   { "NotifyOnClear", 0x00000080 },
   { "DragDrop", 0x00000200 },
   { "NoSelect", 0x00000010 },
   { "NoSelectJmp", 0x00000040 },
   { "UserDrag", 0x00000400 },
   { "AutoDeselect", 0x00000100 },
   { "MultiSelect", 0x00000001 },
   { NULL, 0 }
};

static const struct FieldDef clViewStyle[] = {
   { "List", 0x00000000 },
   { "Icon", 0x00000001 },
   { "Tree", 0x00000002 },
   { "Column", 0x00000003 },
   { "LongList", 0x00000004 },
   { "GroupTree", 0x00000005 },
   { "Document", 0x00000006 },
   { "ColumnTree", 0x00000007 },
   { NULL, 0 }
};

static const struct FieldDef clViewGfxFlags[] = {
   { "OutlineTitle", 0x00000001 },
   { "NoBorder", 0x00000080 },
   { "DrawTable", 0x00000100 },
   { "GroupShadow", 0x00000008 },
   { "Stripes", 0x00000002 },
   { "Hairlines", 0x00000040 },
   { "Branches", 0x00000020 },
   { "AltGroup", 0x00000010 },
   { "LineBreaks", 0x00000004 },
   { NULL, 0 }
};

FDEF maSortColumn[] = { { "Column", FD_STR }, { "Descending", FD_LONG }, { 0, 0 } };
FDEF maSortColumnIndex[] = { { "Column", FD_LONG }, { "Descending", FD_LONG }, { 0, 0 } };
FDEF maSelectItem[] = { { "XPath", FD_STR }, { 0, 0 } };
FDEF maSetItem[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { "Tag", FD_STR }, { "Attrib", FD_STR }, { "Value", FD_STR }, { 0, 0 } };
FDEF maRemoveItem[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { 0, 0 } };
FDEF maRemoveTag[] = { { "TagIndex", FD_LONG }, { "Total", FD_LONG }, { 0, 0 } };
FDEF maRaiseItem[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { 0, 0 } };
FDEF maLowerItem[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { 0, 0 } };
FDEF maCloseBranch[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { 0, 0 } };
FDEF maOpenBranch[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { "Parents", FD_LONG }, { 0, 0 } };
FDEF maInsertItem[] = { { "XPath", FD_STR }, { "TagIndex", FD_LONG }, { "Insert", FD_LONG }, { "XML", FD_STR }, { 0, 0 } };
FDEF maRevealItem[] = { { "TagIndex", FD_LONG }, { 0, 0 } };
FDEF maItemDimensions[] = { { "TagIndex", FD_LONG }, { "X", FD_LONG|FD_RESULT }, { "Y", FD_LONG|FD_RESULT }, { "Width", FD_LONG|FD_RESULT }, { "Height", FD_LONG|FD_RESULT }, { 0, 0 } };

static const struct MethodArray clViewMethods[] = {
   { -3, (APTR)VIEW_SelectAll, "SelectAll", 0, 0 },
   { -4, (APTR)VIEW_InvertSelection, "InvertSelection", 0, 0 },
   { -5, (APTR)VIEW_SortColumn, "SortColumn", maSortColumn, sizeof(struct viewSortColumn) },
   { -6, (APTR)VIEW_SortColumnIndex, "SortColumnIndex", maSortColumnIndex, sizeof(struct viewSortColumnIndex) },
   { -7, (APTR)VIEW_SelectItem, "SelectItem", maSelectItem, sizeof(struct viewSelectItem) },
   { -8, (APTR)VIEW_SetItem, "SetItem", maSetItem, sizeof(struct viewSetItem) },
   { -9, (APTR)VIEW_RemoveItem, "RemoveItem", maRemoveItem, sizeof(struct viewRemoveItem) },
   { -10, (APTR)VIEW_RemoveTag, "RemoveTag", maRemoveTag, sizeof(struct viewRemoveTag) },
   { -11, (APTR)VIEW_SelectNone, "SelectNone", 0, 0 },
   { -12, (APTR)VIEW_RaiseItem, "RaiseItem", maRaiseItem, sizeof(struct viewRaiseItem) },
   { -13, (APTR)VIEW_LowerItem, "LowerItem", maLowerItem, sizeof(struct viewLowerItem) },
   { -14, (APTR)VIEW_CloseBranch, "CloseBranch", maCloseBranch, sizeof(struct viewCloseBranch) },
   { -15, (APTR)VIEW_OpenBranch, "OpenBranch", maOpenBranch, sizeof(struct viewOpenBranch) },
   { -16, (APTR)VIEW_InsertItem, "InsertItem", maInsertItem, sizeof(struct viewInsertItem) },
   { -17, (APTR)VIEW_RevealItem, "RevealItem", maRevealItem, sizeof(struct viewRevealItem) },
   { -18, (APTR)VIEW_ItemDimensions, "ItemDimensions", maItemDimensions, sizeof(struct viewItemDimensions) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clViewActions[] = {
   { AC_ActionNotify, (APTR)VIEW_ActionNotify },
   { AC_Activate, (APTR)VIEW_Activate },
   { AC_Clear, (APTR)VIEW_Clear },
   { AC_DataFeed, (APTR)VIEW_DataFeed },
   { AC_Disable, (APTR)VIEW_Disable },
   { AC_Draw, (APTR)VIEW_Draw },
   { AC_Enable, (APTR)VIEW_Enable },
   { AC_Free, (APTR)VIEW_Free },
   { AC_GetVar, (APTR)VIEW_GetVar },
   { AC_Hide, (APTR)VIEW_Hide },
   { AC_Init, (APTR)VIEW_Init },
   { AC_NewObject, (APTR)VIEW_NewObject },
   { AC_Refresh, (APTR)VIEW_Refresh },
   { AC_ScrollToPoint, (APTR)VIEW_ScrollToPoint },
   { AC_Show, (APTR)VIEW_Show },
   { AC_Sort, (APTR)VIEW_Sort },
   { 0, 0 }
};

