// Auto-generated by idl-c.fluid

namespace xp {
extern ERR Compile(CSTRING Query, struct XPathExpression ** Result);
extern ERR Evaluate(objXML * XML, struct XPathExpression * Query, struct XPathValue ** Result);
extern ERR Query(objXML * XML, struct XPathExpression * Query, FUNCTION * Callback);

} // namespace
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsCompile[] = { { "Error", FD_INT|FD_ERROR }, { "Query", FD_STR }, { "XPathExpression:Result", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF argsEvaluate[] = { { "Error", FD_INT|FD_ERROR }, { "XML", FD_OBJECTPTR }, { "XPathExpression:Query", FD_PTR|FD_STRUCT }, { "XPathValue:Result", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF argsQuery[] = { { "Error", FD_INT|FD_ERROR }, { "XML", FD_OBJECTPTR }, { "Query", FD_PTR }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)xp::Compile, "Compile", argsCompile },
   { (APTR)xp::Evaluate, "Evaluate", argsEvaluate },
   { (APTR)xp::Query, "Query", argsQuery },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "s.XPathExpression:zsOriginal_expression\nc.XPVT:Boolean=0x1,Date=0x4,DateTime=0x6,NodeSet=0x0,Number=0x2,String=0x3,Time=0x5\n"
