// Auto-generated by idl-c.fluid

namespace xp {
extern ERR Compile(objXML * XML, CSTRING Query, struct XPathNode ** Result);
extern ERR Evaluate(objXML * XML, struct XPathNode * Query, struct XPathValue ** Result);
extern ERR Query(objXML * XML, struct XPathNode * Query, FUNCTION * Callback);

} // namespace
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsCompile[] = { { "Error", FD_INT|FD_ERROR }, { "XML", FD_OBJECTPTR }, { "Query", FD_STR }, { "XPathNode:Result", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF argsEvaluate[] = { { "Error", FD_INT|FD_ERROR }, { "XML", FD_OBJECTPTR }, { "XPathNode:Query", FD_PTR|FD_STRUCT }, { "XPathValue:Result", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };
FDEF argsQuery[] = { { "Error", FD_INT|FD_ERROR }, { "XML", FD_OBJECTPTR }, { "Query", FD_PTR }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)xp::Compile, "Compile", argsCompile },
   { (APTR)xp::Evaluate, "Evaluate", argsEvaluate },
   { (APTR)xp::Query, "Query", argsQuery },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "s.XPathNode:\nc.XPathNodeType:ATTRIBUTE_VALUE_TEMPLATE=0x2d,AXIS_SPECIFIER=0x1e,BINARY_OP=0x7,COMMENT_CONSTRUCTOR=0x29,COMPUTED_ATTRIBUTE_CONSTRUCTOR=0x27,COMPUTED_ELEMENT_CONSTRUCTOR=0x26,CONDITIONAL=0x9,CONSTRUCTOR_CONTENT=0x2c,COUNT_CLAUSE=0x14,DIRECT_ATTRIBUTE_CONSTRUCTOR=0x24,DIRECT_ELEMENT_CONSTRUCTOR=0x23,DIRECT_TEXT_CONSTRUCTOR=0x25,DOCUMENT_CONSTRUCTOR=0x2b,EXPRESSION=0x5,FILTER=0x6,FLWOR_EXPRESSION=0xe,FOR_BINDING=0xb,FOR_EXPRESSION=0xa,FUNCTION_CALL=0x17,GROUP_CLAUSE=0x10,GROUP_KEY=0x11,LET_BINDING=0xd,LET_EXPRESSION=0xc,LITERAL=0x18,LOCATION_PATH=0x0,NAME_TEST=0x1a,NODE_TEST=0x2,NODE_TYPE_TEST=0x1b,NUMBER=0x20,ORDER_CLAUSE=0x12,ORDER_SPEC=0x13,PATH=0x22,PI_CONSTRUCTOR=0x2a,PREDICATE=0x3,PROCESSING_INSTRUCTION_TEST=0x1c,QUANTIFIED_BINDING=0x16,QUANTIFIED_EXPRESSION=0x15,ROOT=0x4,STEP=0x1,STRING=0x21,TEXT_CONSTRUCTOR=0x28,UNARY_OP=0x8,UNION=0x1f,VARIABLE_REFERENCE=0x19,WHERE_CLAUSE=0xf,WILDCARD=0x1d\n"
