// Auto-generated by idl-c.fluid

static const struct FieldDef clNetSocketState[] = {
   { "Disconnected", 0x00000000 },
   { "Connecting", 0x00000001 },
   { "ConnectingSSL", 0x00000002 },
   { "Connected", 0x00000003 },
   { nullptr, 0 }
};

static const struct FieldDef clNetSocketFlags[] = {
   { "Server", 0x00000001 },
   { "SSL", 0x00000002 },
   { "MultiConnect", 0x00000004 },
   { "Synchronous", 0x00000008 },
   { "LogAll", 0x00000010 },
   { nullptr, 0 }
};

FDEF maConnect[] = { { "Address", FD_STR }, { "Port", FD_INT }, { 0, 0 } };
FDEF maGetLocalIPAddress[] = { { "IPAddress:Address", FD_PTR|FD_STRUCT }, { 0, 0 } };
FDEF maDisconnectClient[] = { { "Client", FD_OBJECTPTR }, { 0, 0 } };
FDEF maDisconnectSocket[] = { { "Socket", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clNetSocketMethods[] = {
   { AC(-1), (APTR)NETSOCKET_Connect, "Connect", maConnect, sizeof(struct ns::Connect) },
   { AC(-2), (APTR)NETSOCKET_GetLocalIPAddress, "GetLocalIPAddress", maGetLocalIPAddress, sizeof(struct ns::GetLocalIPAddress) },
   { AC(-3), (APTR)NETSOCKET_DisconnectClient, "DisconnectClient", maDisconnectClient, sizeof(struct ns::DisconnectClient) },
   { AC(-4), (APTR)NETSOCKET_DisconnectSocket, "DisconnectSocket", maDisconnectSocket, sizeof(struct ns::DisconnectSocket) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clNetSocketActions[] = {
   { AC::DataFeed, NETSOCKET_DataFeed },
   { AC::Disable, NETSOCKET_Disable },
   { AC::Free, NETSOCKET_Free },
   { AC::FreeWarning, NETSOCKET_FreeWarning },
   { AC::Init, NETSOCKET_Init },
   { AC::NewObject, NETSOCKET_NewObject },
   { AC::NewPlacement, NETSOCKET_NewPlacement },
   { AC::Read, NETSOCKET_Read },
   { AC::Write, NETSOCKET_Write },
   { AC::NIL, nullptr }
};

