// Auto-generated by idl-c.fluid

static const struct FieldDef clConfigFlags[] = {
   { "StripQuotes", 0x00000001 },
   { "AutoSave", 0x00000002 },
   { "OptionalFiles", 0x00000004 },
   { "New", 0x00000008 },
   { nullptr, 0 }
};

FDEF maReadValue[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSet[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR }, { 0, 0 } };
FDEF maWriteValue[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR }, { 0, 0 } };
FDEF maDeleteKey[] = { { "Group", FD_STR }, { "Key", FD_STR }, { 0, 0 } };
FDEF maDeleteGroup[] = { { "Group", FD_STR }, { 0, 0 } };
FDEF maGetGroupFromIndex[] = { { "Index", FD_INT }, { "Group", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSortByKey[] = { { "Key", FD_STR }, { "Descending", FD_INT }, { 0, 0 } };
FDEF maMergeFile[] = { { "Path", FD_STR }, { 0, 0 } };
FDEF maMerge[] = { { "Source", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clConfigMethods[] = {
   { AC(-1), (APTR)CONFIG_ReadValue, "ReadValue", maReadValue, sizeof(struct cfg::ReadValue) },
   { AC(-2), (APTR)CONFIG_Set, "Set", maSet, sizeof(struct cfg::Set) },
   { AC(-3), (APTR)CONFIG_WriteValue, "WriteValue", maWriteValue, sizeof(struct cfg::WriteValue) },
   { AC(-4), (APTR)CONFIG_DeleteKey, "DeleteKey", maDeleteKey, sizeof(struct cfg::DeleteKey) },
   { AC(-5), (APTR)CONFIG_DeleteGroup, "DeleteGroup", maDeleteGroup, sizeof(struct cfg::DeleteGroup) },
   { AC(-6), (APTR)CONFIG_GetGroupFromIndex, "GetGroupFromIndex", maGetGroupFromIndex, sizeof(struct cfg::GetGroupFromIndex) },
   { AC(-7), (APTR)CONFIG_SortByKey, "SortByKey", maSortByKey, sizeof(struct cfg::SortByKey) },
   { AC(-9), (APTR)CONFIG_MergeFile, "MergeFile", maMergeFile, sizeof(struct cfg::MergeFile) },
   { AC(-10), (APTR)CONFIG_Merge, "Merge", maMerge, sizeof(struct cfg::Merge) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clConfigActions[] = {
   { AC::Clear, CONFIG_Clear },
   { AC::DataFeed, CONFIG_DataFeed },
   { AC::Flush, CONFIG_Flush },
   { AC::Free, CONFIG_Free },
   { AC::Init, CONFIG_Init },
   { AC::NewObject, CONFIG_NewObject },
   { AC::SaveSettings, CONFIG_SaveSettings },
   { AC::SaveToObject, CONFIG_SaveToObject },
   { AC::NIL, nullptr }
};

