// Auto-generated by idl-c.fluid

static const struct FieldDef clScriptFlags[] = {
   { "ExitOnError", 0x00000001 },
   { "LogAll", 0x00000002 },
   { NULL, 0 }
};

FDEF maExec[] = { { "Procedure", FD_STR }, { "ScriptArg:Args", FD_PTR|FD_STRUCT }, { "TotalArgs", FD_LONG }, { 0, 0 } };
FDEF maDerefProcedure[] = { { "Procedure", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maCallback[] = { { "ProcedureID", FD_LARGE }, { "ScriptArg:Args", FD_PTR|FD_STRUCT }, { "TotalArgs", FD_LONG }, { "Error", FD_LONG|FD_ERROR|FD_RESULT }, { 0, 0 } };
FDEF maGetProcedureID[] = { { "Procedure", FD_STR }, { "ProcedureID", FD_LARGE|FD_RESULT }, { 0, 0 } };

static const struct MethodEntry clScriptMethods[] = {
   { AC(-1), (APTR)SCRIPT_Exec, "Exec", maExec, sizeof(struct sc::Exec) },
   { AC(-2), (APTR)SCRIPT_DerefProcedure, "DerefProcedure", maDerefProcedure, sizeof(struct sc::DerefProcedure) },
   { AC(-3), (APTR)SCRIPT_Callback, "Callback", maCallback, sizeof(struct sc::Callback) },
   { AC(-4), (APTR)SCRIPT_GetProcedureID, "GetProcedureID", maGetProcedureID, sizeof(struct sc::GetProcedureID) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clScriptActions[] = {
   { AC::Activate, SCRIPT_Activate },
   { AC::DataFeed, SCRIPT_DataFeed },
   { AC::Free, SCRIPT_Free },
   { AC::GetKey, SCRIPT_GetKey },
   { AC::Init, SCRIPT_Init },
   { AC::NewObject, SCRIPT_NewObject },
   { AC::Reset, SCRIPT_Reset },
   { AC::SetKey, SCRIPT_SetKey },
   { AC::NIL, NULL }
};

