// Auto-generated by idl-c.fluid

FDEF maAddArgument[] = { { "Argument", FD_STR }, { 0, 0 } };
FDEF maGetEnv[] = { { "Name", FD_STR }, { "Value", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSetEnv[] = { { "Name", FD_STR }, { "Value", FD_STR }, { 0, 0 } };

static const struct MethodArray clTaskMethods[] = {
   { -1, (APTR)TASK_Expunge, "Expunge", 0, 0 },
   { -2, (APTR)TASK_AddArgument, "AddArgument", maAddArgument, sizeof(struct taskAddArgument) },
   { -3, (APTR)TASK_Quit, "Quit", 0, 0 },
   { -4, (APTR)TASK_GetEnv, "GetEnv", maGetEnv, sizeof(struct taskGetEnv) },
   { -5, (APTR)TASK_SetEnv, "SetEnv", maSetEnv, sizeof(struct taskSetEnv) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clTaskActions[] = {
   { AC_Activate, TASK_Activate },
   { AC_Free, TASK_Free },
   { AC_GetVar, TASK_GetVar },
   { AC_Init, TASK_Init },
   { AC_NewObject, TASK_NewObject },
   { AC_SetVar, TASK_SetVar },
   { AC_Write, TASK_Write },
   { 0, NULL }
};

