// Auto-generated by idl-c.fluid

static const struct FieldDef clConfigFlags[] = {
   { "StripQuotes", 0x00000001 },
   { "AutoSave", 0x00000002 },
   { "OptionalFiles", 0x00000004 },
   { "New", 0x00000008 },
   { NULL, 0 }
};

FDEF maReadValue[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSet[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR }, { 0, 0 } };
FDEF maWriteValue[] = { { "Group", FD_STR }, { "Key", FD_STR }, { "Data", FD_STR }, { 0, 0 } };
FDEF maDeleteKey[] = { { "Group", FD_STR }, { "Key", FD_STR }, { 0, 0 } };
FDEF maDeleteGroup[] = { { "Group", FD_STR }, { 0, 0 } };
FDEF maGetGroupFromIndex[] = { { "Index", FD_LONG }, { "Group", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSortByKey[] = { { "Key", FD_STR }, { "Descending", FD_LONG }, { 0, 0 } };
FDEF maMergeFile[] = { { "Path", FD_STR }, { 0, 0 } };
FDEF maMerge[] = { { "Source", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clConfigMethods[] = {
   { -1, (APTR)CONFIG_ReadValue, "ReadValue", maReadValue, sizeof(struct cfgReadValue) },
   { -2, (APTR)CONFIG_Set, "Set", maSet, sizeof(struct cfgSet) },
   { -3, (APTR)CONFIG_WriteValue, "WriteValue", maWriteValue, sizeof(struct cfgWriteValue) },
   { -4, (APTR)CONFIG_DeleteKey, "DeleteKey", maDeleteKey, sizeof(struct cfgDeleteKey) },
   { -5, (APTR)CONFIG_DeleteGroup, "DeleteGroup", maDeleteGroup, sizeof(struct cfgDeleteGroup) },
   { -6, (APTR)CONFIG_GetGroupFromIndex, "GetGroupFromIndex", maGetGroupFromIndex, sizeof(struct cfgGetGroupFromIndex) },
   { -7, (APTR)CONFIG_SortByKey, "SortByKey", maSortByKey, sizeof(struct cfgSortByKey) },
   { -9, (APTR)CONFIG_MergeFile, "MergeFile", maMergeFile, sizeof(struct cfgMergeFile) },
   { -10, (APTR)CONFIG_Merge, "Merge", maMerge, sizeof(struct cfgMerge) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clConfigActions[] = {
   { AC_Clear, CONFIG_Clear },
   { AC_DataFeed, CONFIG_DataFeed },
   { AC_Flush, CONFIG_Flush },
   { AC_Free, CONFIG_Free },
   { AC_Init, CONFIG_Init },
   { AC_NewObject, CONFIG_NewObject },
   { AC_SaveSettings, CONFIG_SaveSettings },
   { AC_SaveToObject, CONFIG_SaveToObject },
   { AC_Sort, CONFIG_Sort },
   { 0, NULL }
};

