// Auto-generated by idl-c.fluid

FDEF maAddArgument[] = { { "Argument", FD_STR }, { 0, 0 } };
FDEF maGetEnv[] = { { "Name", FD_STR }, { "Value", FD_STR|FD_RESULT }, { 0, 0 } };
FDEF maSetEnv[] = { { "Name", FD_STR }, { "Value", FD_STR }, { 0, 0 } };

static const struct MethodArray clTaskMethods[] = {
   { -1, (APTR)TASK_Expunge, "Expunge", 0, 0 },
   { -2, (APTR)TASK_AddArgument, "AddArgument", maAddArgument, sizeof(struct taskAddArgument) },
   { -3, (APTR)TASK_Quit, "Quit", 0, 0 },
   { -4, (APTR)TASK_GetEnv, "GetEnv", maGetEnv, sizeof(struct taskGetEnv) },
   { -5, (APTR)TASK_SetEnv, "SetEnv", maSetEnv, sizeof(struct taskSetEnv) },
   { -6, (APTR)TASK_CloseInstance, "CloseInstance", 0, 0 },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clTaskActions[] = {
   { AC_ActionNotify, (APTR)TASK_ActionNotify },
   { AC_Activate, (APTR)TASK_Activate },
   { AC_Free, (APTR)TASK_Free },
   { AC_GetVar, (APTR)TASK_GetVar },
   { AC_Init, (APTR)TASK_Init },
   { AC_NewObject, (APTR)TASK_NewObject },
   { AC_ReleaseObject, (APTR)TASK_ReleaseObject },
   { AC_SetVar, (APTR)TASK_SetVar },
   { AC_Write, (APTR)TASK_Write },
   { 0, 0 }
};

