// Auto-generated by idl-c.fluid

#ifdef  __cplusplus
extern "C" {
#endif

static ERROR sndStartDrivers();
static ERROR sndWaitDrivers(LONG TimeOut);
static LONG sndSetChannels(LONG Total);
static DOUBLE sndSetTaskVolume(DOUBLE Volume);

#ifdef  __cplusplus
}
#endif
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsSetChannels[] = { { "Result", FD_LONG }, { "Total", FD_LONG }, { 0, 0 } };
FDEF argsSetTaskVolume[] = { { "Result", FD_DOUBLE }, { "Volume", FD_DOUBLE }, { 0, 0 } };
FDEF argsStartDrivers[] = { { "Error", FD_LONG|FD_ERROR }, { 0, 0 } };
FDEF argsWaitDrivers[] = { { "Error", FD_LONG|FD_ERROR }, { "TimeOut", FD_LONG }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)sndStartDrivers, "StartDrivers", argsStartDrivers },
   { (APTR)sndWaitDrivers, "WaitDrivers", argsWaitDrivers },
   { (APTR)sndSetChannels, "SetChannels", argsSetChannels },
   { (APTR)sndSetTaskVolume, "SetTaskVolume", argsSetTaskVolume },
   { NULL, NULL, NULL }
};

#undef MOD_IDL
#define MOD_IDL "s.AudioSample:pData,lStreamID,lSampleLength,lLoop1Start,lLoop1End,lLoop2Start,lLoop2End,lSeekStart,lStreamLength,lBufferLength,lStreamPos,ucSampleType,cLoopMode,cLoop1Type,cLoop2Type,cUsed,cFree\ns.AudioChannel:eSample:AudioSample,lSoundID,lSampleHandle,lFlags,ulPosition,ulFrequency,uwPositionLow,wLVolume,wRVolume,wLVolumeTarget,wRVolumeTarget,wVolume,cPriority,cState[CHS],cLoopIndex,cPan\ns.AudioCommand:lCommandID,lHandle,lData\ns.ChannelSet:pChannel:AudioChannel,pCommands:AudioCommand,lUpdateRate,lMixLeft,lKey,lTaskID,lChannelMID,lCommandMID,dTaskVolume,wTotal,wActual,wTotalCommands,wPosition,wOpenCount\ns.VolumeCtl:wSize,cName[32],lFlags,fChannels[1]\ns.AudioLoop:wLoopMode,cLoop1Type[LTYPE],cLoop2Type[LTYPE],lLoop1Start,lLoop1End,lLoop2Start,lLoop2End\nc.LOOP:AMIGA=0x5,SINGLE=0x1,SINGLE_RELEASE=0x2,DOUBLE=0x3,AMIGA_NONE=0x4\nc.SFM:U8_BIT_STEREO=0x3,S16_BIT_STEREO=0x4,U8_BIT_MONO=0x1,END=0x5,BIG_ENDIAN=0x80000000,S16_BIT_MONO=0x2\nc.CHF:BACKWARD=0x2,CHANGED=0x8,VOL_RAMP=0x4,MUTE=0x1\nc.VCF:CAPTURE=0x10,JOINED=0x100,SYNC=0x100000,MONO=0x1000,MUTE=0x10000,PLAYBACK=0x1\nc.SDF:LOOP=0x1,STEREO=0x8,TERMINATE=0x10,NOTE=0x80000000,RESTRICT_PLAY=0x20,NEW=0x2,STREAM=0x40000000,QUERY=0x4\nc.LTYPE:BIDIRECTIONAL=0x2,UNIDIRECTIONAL=0x1\nc.SVF:CAPTURE=0x10000,UNMUTE=0x1000,UNSYNC=0x1000000,SYNC=0x100000,MUTE=0x100\nc.ADF:SERVICE_MODE=0x80,STEREO=0x8,OVER_SAMPLING=0x1,VOL_RAMPING=0x10,SYSTEM_WIDE=0x40,FILTER_LOW=0x2,AUTO_SAVE=0x20,FILTER_HIGH=0x4\nc.CHS:PLAYING=0x2,RELEASED=0x3,FADE_OUT=0x4,STOPPED=0x0,FINISHED=0x1\nc.NOTE:FS=0x6,G=0x7,GS=0x8,A=0x9,AS=0xa,B=0xb,OCTAVE=0xc,C=0x0,CS=0x1,D=0x2,DS=0x3,E=0x4,F=0x5\nc.STREAM:SMART=0x2,ALWAYS=0x3,NEVER=0x1\nc.CMD:FADE_OUT=0xc,SET_LENGTH=0xe,CONTINUE=0xf,START_SEQUENCE=0x0,END_SEQUENCE=0x1,SET_SAMPLE=0x2,SET_VOLUME=0x3,SET_PAN=0x4,SET_FREQUENCY=0x5,SET_RATE=0x6,STOP=0x7,STOP_LOOPING=0x8,SET_POSITION=0x9,PLAY=0xa,FADE_IN=0xb,MUTE=0xd\n"
