// Auto-generated by idl-c.fluid

#ifdef  __cplusplus
extern "C" {
#endif

static ERROR sndMixContinue(objAudio * Audio, LONG Handle);
static ERROR sndMixFrequency(objAudio * Audio, LONG Handle, LONG Frequency);
static ERROR sndMixMute(objAudio * Audio, LONG Handle, LONG Mute);
static ERROR sndMixPan(objAudio * Audio, LONG Handle, DOUBLE Pan);
static ERROR sndMixPlay(objAudio * Audio, LONG Handle, LONG Position);
static ERROR sndMixRate(objAudio * Audio, LONG Handle, LONG Rate);
static ERROR sndMixSample(objAudio * Audio, LONG Handle, LONG Sample);
static ERROR sndMixStop(objAudio * Audio, LONG Handle);
static ERROR sndMixStopLoop(objAudio * Audio, LONG Handle);
static ERROR sndMixVolume(objAudio * Audio, LONG Handle, DOUBLE Volume);
static ERROR sndMixStartSequence(objAudio * Audio, LONG Handle);
static ERROR sndMixEndSequence(objAudio * Audio, LONG Handle);

#ifdef  __cplusplus
}
#endif
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsMixContinue[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { 0, 0 } };
FDEF argsMixEndSequence[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { 0, 0 } };
FDEF argsMixFrequency[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Frequency", FD_LONG }, { 0, 0 } };
FDEF argsMixMute[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Mute", FD_LONG }, { 0, 0 } };
FDEF argsMixPan[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Pan", FD_DOUBLE }, { 0, 0 } };
FDEF argsMixPlay[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Position", FD_LONG }, { 0, 0 } };
FDEF argsMixRate[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Rate", FD_LONG }, { 0, 0 } };
FDEF argsMixSample[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Sample", FD_LONG }, { 0, 0 } };
FDEF argsMixStartSequence[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { 0, 0 } };
FDEF argsMixStop[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { 0, 0 } };
FDEF argsMixStopLoop[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { 0, 0 } };
FDEF argsMixVolume[] = { { "Error", FD_LONG|FD_ERROR }, { "Audio", FD_OBJECTPTR }, { "Handle", FD_LONG }, { "Volume", FD_DOUBLE }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)sndMixContinue, "MixContinue", argsMixContinue },
   { (APTR)sndMixFrequency, "MixFrequency", argsMixFrequency },
   { (APTR)sndMixMute, "MixMute", argsMixMute },
   { (APTR)sndMixPan, "MixPan", argsMixPan },
   { (APTR)sndMixPlay, "MixPlay", argsMixPlay },
   { (APTR)sndMixRate, "MixRate", argsMixRate },
   { (APTR)sndMixSample, "MixSample", argsMixSample },
   { (APTR)sndMixStop, "MixStop", argsMixStop },
   { (APTR)sndMixStopLoop, "MixStopLoop", argsMixStopLoop },
   { (APTR)sndMixVolume, "MixVolume", argsMixVolume },
   { (APTR)sndMixStartSequence, "MixStartSequence", argsMixStartSequence },
   { (APTR)sndMixEndSequence, "MixEndSequence", argsMixEndSequence },
   { NULL, NULL, NULL }
};

#undef MOD_IDL
#define MOD_IDL "s.AudioLoop:wLoopMode,cLoop1Type[LTYPE],cLoop2Type[LTYPE],lLoop1Start,lLoop1End,lLoop2Start,lLoop2End\nc.ADF:AUTO_SAVE=0x20,FILTER_HIGH=0x4,FILTER_LOW=0x2,OVER_SAMPLING=0x1,STEREO=0x8,SYSTEM_WIDE=0x40,VOL_RAMPING=0x10\nc.CHF:BACKWARD=0x2,CHANGED=0x8,MUTE=0x1,VOL_RAMP=0x4\nc.CHS:FADE_OUT=0x4,FINISHED=0x1,PLAYING=0x2,RELEASED=0x3,STOPPED=0x0\nc.LOOP:AMIGA=0x5,AMIGA_NONE=0x4,DOUBLE=0x3,SINGLE=0x1,SINGLE_RELEASE=0x2\nc.LTYPE:BIDIRECTIONAL=0x2,UNIDIRECTIONAL=0x1\nc.NOTE:A=0x9,AS=0xa,B=0xb,C=0x0,CS=0x1,D=0x2,DS=0x3,E=0x4,F=0x5,FS=0x6,G=0x7,GS=0x8,OCTAVE=0xc\nc.SDF:LOOP=0x1,NEW=0x2,NOTE=0x80000000,RESTRICT_PLAY=0x8,STEREO=0x4,STREAM=0x40000000\nc.SFM:BIG_ENDIAN=0x80000000,END=0x5,S16_BIT_MONO=0x2,S16_BIT_STEREO=0x4,U8_BIT_MONO=0x1,U8_BIT_STEREO=0x3\nc.STREAM:ALWAYS=0x3,NEVER=0x1,SMART=0x2\nc.SVF:CAPTURE=0x10000,MUTE=0x100,SYNC=0x100000,UNMUTE=0x1000,UNSYNC=0x1000000\nc.VCF:CAPTURE=0x10,JOINED=0x100,MONO=0x1000,MUTE=0x10000,PLAYBACK=0x1,SYNC=0x100000\n"
