#ifndef SYSTEM_ERRORS
#define SYSTEM_ERRORS 1

// Name:      system/errors.h
// Copyright: Paul Manias © 1996-2017
// Generator: idl-c

// Universal error codes

#define ERR_Okay 0
#define ERR_True 0
#define ERR_False 1
#define ERR_LimitedSuccess 2
#define ERR_Cancelled 3
#define ERR_NothingDone 4
#define ERR_Continue 5
#define ERR_Skip 6
#define ERR_Retry 7
#define ERR_DirEmpty 8
#define ERR_Terminate 9
#define ERR_NoMemory 10
#define ERR_NoPointer 11
#define ERR_InUse 12
#define ERR_Failed 13
#define ERR_File 14
#define ERR_InvalidData 15
#define ERR_Search 16
#define ERR_NotFound 16
#define ERR_InitModule 17
#define ERR_FileNotFound 18
#define ERR_WrongVersion 19
#define ERR_Args 20
#define ERR_NoData 21
#define ERR_Read 22
#define ERR_Write 23
#define ERR_LockFailed 24
#define ERR_Lock 24
#define ERR_ExamineFailed 25
#define ERR_LostClass 26
#define ERR_NoAction 27
#define ERR_NoSupport 28
#define ERR_Memory 29
#define ERR_TimeOut 30
#define ERR_NoStats 31
#define ERR_LowCapacity 32
#define ERR_Init 33
#define ERR_NoPermission 34
#define ERR_Permissions 34
#define ERR_PermissionDenied 34
#define ERR_SystemCorrupt 35
#define ERR_NeedOwner 36
#define ERR_OwnerNeedsBitmap 37
#define ERR_CoreVersion 38
#define ERR_NeedWidthHeight 39
#define ERR_NegativeSubClassID 40
#define ERR_NegativeClassID 41
#define ERR_MissingClassName 42
#define ERR_OutOfRange 43
#define ERR_ObtainMethod 44
#define ERR_ArrayFull 45
#define ERR_Query 46
#define ERR_LostOwner 47
#define ERR_DoNotExpunge 48
#define ERR_MemoryCorrupt 49
#define ERR_FieldSearch 50
#define ERR_InvalidPath 51
#define ERR_SetField 52
#define ERR_MarkedForDeletion 53
#define ERR_IllegalMethodID 54
#define ERR_IllegalActionID 55
#define ERR_ModuleOpenFailed 56
#define ERR_IllegalActionAttempt 57
#define ERR_EntryMissingHeader 58
#define ERR_ModuleMissingInit 59
#define ERR_ModuleInitFailed 60
#define ERR_MemoryDoesNotExist 61
#define ERR_DeadLock 62
#define ERR_SystemLocked 63
#define ERR_ModuleMissingName 64
#define ERR_AddClass 65
#define ERR_Activate 66
#define ERR_DoubleInit 67
#define ERR_FieldNotSet 68
#define ERR_MissingClass 69
#define ERR_FileReadFlag 70
#define ERR_FileWriteFlag 71
#define ERR_Draw 72
#define ERR_NoMethods 73
#define ERR_NoMatchingObject 74
#define ERR_AccessMemory 75
#define ERR_MissingPath 76
#define ERR_NotLocked 77
#define ERR_NoSearchResult 78
#define ERR_StatementUnsatisfied 79
#define ERR_ObjectCorrupt 80
#define ERR_OwnerPassThrough 81
#define ERR_UnsupportedOwner 82
#define ERR_BadOwner 82
#define ERR_ExclusiveDenied 83
#define ERR_AccessObject 83
#define ERR_AllocMemory 84
#define ERR_NewObject 85
#define ERR_GetField 86
#define ERR_NoFieldAccess 87
#define ERR_VirtualVolume 88
#define ERR_InvalidDimension 89
#define ERR_FieldTypeMismatch 90
#define ERR_UnrecognisedFieldType 91
#define ERR_BufferOverflow 92
#define ERR_UnsupportedField 93
#define ERR_Mismatch 94
#define ERR_OutOfBounds 95
#define ERR_Seek 96
#define ERR_ReallocMemory 97
#define ERR_Loop 98
#define ERR_FileExists 99
#define ERR_ResolvePath 100
#define ERR_CreateObject 101
#define ERR_MemoryInfo 102
#define ERR_NotInitialised 103
#define ERR_ResourceExists 104
#define ERR_Refresh 105
#define ERR_ListChildren 106
#define ERR_SystemCall 107
#define ERR_SmallMask 108
#define ERR_EmptyString 109
#define ERR_ObjectExists 110
#define ERR_ExpectedFile 111
#define ERR_Resize 112
#define ERR_Redimension 113
#define ERR_AllocSemaphore 114
#define ERR_AccessSemaphore 115
#define ERR_CreateFile 116
#define ERR_DeleteFile 117
#define ERR_OpenFile 118
#define ERR_ReadOnly 119
#define ERR_DoesNotExist 120
#define ERR_IdenticalPaths 121
#define ERR_Exists 122
#define ERR_SanityFailure 123
#define ERR_OutOfSpace 124
#define ERR_GetSurfaceInfo 125
#define ERR_Finished 126
#define ERR_EOF 126
#define ERR_EndOfFile 126
#define ERR_OutOfData 126
#define ERR_Syntax 127
#define ERR_StringFormat 127
#define ERR_BadState 128
#define ERR_HostNotFound 129
#define ERR_InvalidURI 130
#define ERR_ConnectionRefused 131
#define ERR_NetworkUnreachable 132
#define ERR_HostUnreachable 133
#define ERR_Disconnected 134
#define ERR_TaskStillExists 135
#define ERR_IntegrityViolation 136
#define ERR_ConstraintViolation 136
#define ERR_SchemaViolation 137
#define ERR_DataSize 138
#define ERR_Busy 139
#define ERR_ConnectionAborted 140
#define ERR_NullArgs 141
#define ERR_InvalidObject 142
#define ERR_WrongObjectType 142
#define ERR_WrongClass 142
#define ERR_ExecViolation 143
#define ERR_Recursion 144
#define ERR_IllegalAddress 145
#define ERR_UnbalancedXML 146
#define ERR_WouldBlock 147
#define ERR_InputOutput 148
#define ERR_LoadModule 149
#define ERR_InvalidHandle 150
#define ERR_Security 151
#define ERR_InvalidValue 152
#define ERR_ServiceUnavailable 153
#define ERR_Deactivated 154
#define ERR_LockRequired 155
#define ERR_AlreadyLocked 156
#define ERR_Locked 156
#define ERR_CardReaderUnknown 157
#define ERR_NoMediaInserted 158
#define ERR_CardReaderUnavailable 159
#define ERR_ProxySSLTunnel 160
#define ERR_InvalidHTTPResponse 161
#define ERR_InvalidReference 162
#define ERR_Exception 163
#define ERR_GlobalInstanceLocked 164
#define ERR_OpenGL 165
#define ERR_OutsideMainThread 166
#define ERR_UseSubClass 167
#define ERR_WrongType 168
#define ERR_AllocMutex 169
#define ERR_LockMutex 170
#define ERR_SetVolume 171
#define ERR_Decompression 172
#define ERR_Compression 173
#define ERR_ExpectedFolder 174
#define ERR_Immutable 175
#define ERR_ReadFile 176
#define ERR_Obsolete 177
#define ERR_END 178

// Error headers

#define ERH_AccessMemory 1
#define ERH_Action 2
#define ERH_ActionMsg 3
#define ERH_AddMemEntry 4
#define ERH_ActionNotify 5
#define ERH_Activate 6
#define ERH_AddClass 7
#define ERH_AddPrivateObject 8
#define ERH_AddSharedObject 9
#define ERH_AllocMemory 10
#define ERH_Volume 11
#define ERH_AccessObject 12
#define ERH_Bitmap 13
#define ERH_Broadcast 14
#define ERH_Broadcaster 15
#define ERH_CheckAction 16
#define ERH_CheckInit 17
#define ERH_CheckObjectExists 18
#define ERH_Class 19
#define ERH_Clear 20
#define ERH_CloneMemory 21
#define ERH_CloseFeed 22
#define ERH_CloseModule 23
#define ERH_UpdateTimer 24
#define ERH_IdentifyFile 25
#define ERH_CopyArguments 26
#define ERH_CopyData 27
#define ERH_DataFeed 28
#define ERH_Deactivate 29
#define ERH_DeleteVolume 30
#define ERH_Draw 31
#define ERH_Error 32
#define ERH_Event 33
#define ERH_ExpungeModule 34
#define ERH_File 35
#define ERH_FileSystem 36
#define ERH_FindChildren 37
#define ERH_FindClass 38
#define ERH_ResolveClassName 39
#define ERH_FindField 40
#define ERH_FindObject 41
#define ERH_Flush 42
#define ERH_Focus 43
#define ERH_Free 44
#define ERH_FreeClass 45
#define ERH_ReleaseObject 46
#define ERH_FreeMemory 47
#define ERH_FreeMemoryID 48
#define ERH_FreeResource 49
#define ERH_GetClassID 50
#define ERH_GetField 51
#define ERH_GetName 52
#define ERH_Hide 53
#define ERH_Init 54
#define ERH_InitModule 55
#define ERH_Core 56
#define ERH_ListChildren 57
#define ERH_LoadFromObject 58
#define ERH_ManageAction 59
#define ERH_MemoryIDInfo 60
#define ERH_Method 61
#define ERH_GetDeviceInfo 62
#define ERH_Module 63
#define ERH_Move 64
#define ERH_MoveToFront 65
#define ERH_MoveToBack 66
#define ERH_NewClass 67
#define ERH_NewObject 68
#define ERH_NotifySubscribers 69
#define ERH_ObtainMethod 70
#define ERH_SubscribeFeed 71
#define ERH_OpenModule 72
#define ERH_Parasol 73
#define ERH_Pointer 74
#define ERH_ProcessMessages 75
#define ERH_Query 76
#define ERH_Read 77
#define ERH_ReadConfig 78
#define ERH_Realloc 79
#define ERH_GetMessage 80
#define ERH_ReleaseMemory 81
#define ERH_RemoveObject 82
#define ERH_Rename 83
#define ERH_Reset 84
#define ERH_Resize 85
#define ERH_ResolvePath 86
#define ERH_SaveImage 87
#define ERH_SaveToObject 88
#define ERH_Screen 89
#define ERH_Script 90
#define ERH_Scroll 91
#define ERH_Seek 92
#define ERH_SetOwner 93
#define ERH_SetField 94
#define ERH_SetVar 95
#define ERH_SendMessage 96
#define ERH_Show 97
#define ERH_SetName 98
#define ERH_Strings 99
#define ERH_StrReplace 100
#define ERH_StrSearch 101
#define ERH_SubscribeAction 102
#define ERH_SubscribeTimer 103
#define ERH_Subscriber 104
#define ERH_TotalChildren 105
#define ERH_UserClick 106
#define ERH_UserMovement 107
#define ERH_Unhook 108
#define ERH_UnsubscribeAction 109
#define ERH_Write 110
#define ERH_NewChild 111
#define ERH_CopyFile 112
#define ERH_SubscribeEvent 113
#define ERH_UnsubscribeEvent 114
#define ERH_Function 115
#define ERH_FastFindObject 116
#define ERH_Clipboard 117
#define ERH_Refresh 118
#define ERH_XML 119
#define ERH_ConvertFontCoords 120
#define ERH_CalcStringWidth 121
#define ERH_CreateObject 122
#define ERH_CheckMemoryExists 123
#define ERH_SleepingTask 124
#define ERH_SetContext 125
#define ERH_UnsubscribeFeed 126
#define ERH_UnsubscribeTimer 127
#define ERH_AllocateID 128
#define ERH_GetOwnerID 129
#define ERH_ActionTags 130
#define ERH_GetFields 131
#define ERH_SetFields 132
#define ERH_GetFieldVariable 133
#define ERH_SetFieldEval 134
#define ERH_LogError 135
#define ERH_ReallocMemory 136
#define ERH_MemoryPtrInfo 137
#define ERH_Redimension 138
#define ERH_ScanMessages 139
#define ERH_Timer 140
#define ERH_AccessSemaphore 141
#define ERH_ReleaseSemaphore 142
#define ERH_AllocSemaphore 143
#define ERH_FreeSemaphore 144
#define ERH_SetDimension 145
#define ERH_GetDimension 146
#define ERH_GetVar 147
#define ERH_MoveToPoint 148
#define ERH_ScrollToPoint 149
#define ERH_SetWidth 150
#define ERH_SetHeight 151
#define ERH_SetX 152
#define ERH_SetY 153
#define ERH_SetXOffset 154
#define ERH_SetYOffset 155
#define ERH_GetWidth 156
#define ERH_GetHeight 157
#define ERH_GetX 158
#define ERH_GetY 159
#define ERH_GetXOffset 160
#define ERH_GetYOffset 161
#define ERH_ListTasks 162
#define ERH_LostFocus 163
#define ERH_UpdateMessage 164
#define ERH_ValidateProcess 165
#define ERH_UserClickRelease 166
#define ERH_ListObjects 167
#define ERH_FindPrivateObject 168
#define ERH_RegisterFD 169
#define ERH_AccessSurface 170
#define ERH_ReleaseSurface 171
#define ERH_LockBitmap 172
#define ERH_UnlockBitmap 173
#define ERH_CopySurface 174
#define ERH_GetSurfaceInfo 175
#define ERH_SetRegion 176
#define ERH_Sort 177
#define ERH_TranslateText 178
#define ERH_TranslateRefresh 179
#define ERH_SaveSettings 180
#define ERH_Custom 181
#define ERH_WatchFile 182
#define ERH_GetFileInfo 183
#define ERH_FindPublicObject 184
#define ERH_BuildJumpTable 185
#define ERH_CheckResident 186
#define ERH_Android 187
#define ERH_Display 188
#define ERH_CoreSleep 189
#define ERH_LoadModules 190
#define ERH_LoadClasses 191
#define ERH_CopyArea 192
#define ERH_CopyStretch 193
#define ERH_SetCursor 194
#define ERH_UnlockCursor 195
#define ERH_DrawRectangle 196
#define ERH_OpenDir 197
#define ERH_ScanDir 198
#define ERH_END 199

// Special error flags

#define ERF_Notified 1073741824
#define ERF_Delay 536870912

#endif
