// Auto-generated by idl-c.fluid

static const struct FieldDef clSurfaceFlags[] = {
   { "Transparent", 0x00000001 },
   { "StickToBack", 0x00000002 },
   { "StickToFront", 0x00000004 },
   { "Visible", 0x00000008 },
   { "Sticky", 0x00000010 },
   { "GrabFocus", 0x00000020 },
   { "HasFocus", 0x00000040 },
   { "Disabled", 0x00000080 },
   { "AutoQuit", 0x00000100 },
   { "Host", 0x00000200 },
   { "Precopy", 0x00000400 },
   { "Video", 0x00000800 },
   { "WriteOnly", 0x00000800 },
   { "NoHorizontal", 0x00001000 },
   { "NoVertical", 0x00002000 },
   { "Cursor", 0x00004000 },
   { "Pointer", 0x00004000 },
   { "AfterCopy", 0x00008000 },
   { "ReadOnly", 0x0000c040 },
   { "Volatile", 0x0000c400 },
   { "FixedBuffer", 0x00010000 },
   { "PervasiveCopy", 0x00020000 },
   { "NoFocus", 0x00040000 },
   { "FixedDepth", 0x00080000 },
   { "TotalRedraw", 0x00100000 },
   { "Composite", 0x00200000 },
   { "NoPrecomposite", 0x00200000 },
   { "PostComposite", 0x00200000 },
   { "FullScreen", 0x00400000 },
   { "IgnoreFocus", 0x00800000 },
   { "InitOnly", 0x00cb0e81 },
   { "AspectRatio", 0x01000000 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceAlign[] = {
   { "Left", 0x00000001 },
   { "Right", 0x00000002 },
   { "Horizontal", 0x00000004 },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Middle", 0x0000000c },
   { "Top", 0x00000010 },
   { "Bottom", 0x00000020 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceDimensions[] = {
   { "ScaledX", 0x00000001 },
   { "ScaledY", 0x00000002 },
   { "FixedX", 0x00000004 },
   { "FixedY", 0x00000008 },
   { "ScaledXOffset", 0x00000010 },
   { "ScaledYOffset", 0x00000020 },
   { "FixedXOffset", 0x00000040 },
   { "FixedYOffset", 0x00000080 },
   { "FixedHeight", 0x00000100 },
   { "FixedWidth", 0x00000200 },
   { "ScaledHeight", 0x00000400 },
   { "ScaledWidth", 0x00000800 },
   { "FixedDepth", 0x00001000 },
   { "ScaledDepth", 0x00002000 },
   { "FixedZ", 0x00004000 },
   { "ScaledZ", 0x00008000 },
   { "ScaledRadiusX", 0x00010000 },
   { "FixedRadiusX", 0x00020000 },
   { "ScaledCenterX", 0x00040000 },
   { "ScaledCenterY", 0x00080000 },
   { "FixedCenterX", 0x00100000 },
   { "FixedCenterY", 0x00200000 },
   { "StatusChangeH", 0x00400000 },
   { "StatusChangeV", 0x00800000 },
   { "ScaledRadiusY", 0x01000000 },
   { "FixedRadiusY", 0x02000000 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceDragStatus[] = {
   { "None", 0x00000000 },
   { "Anchor", 0x00000001 },
   { "Normal", 0x00000002 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceCursor[] = {
   { "NoChange", 0x00000000 },
   { "Default", 0x00000001 },
   { "SizeBottomLeft", 0x00000002 },
   { "SizeBottomRight", 0x00000003 },
   { "SizeTopLeft", 0x00000004 },
   { "SizeTopRight", 0x00000005 },
   { "SizeLeft", 0x00000006 },
   { "SizeRight", 0x00000007 },
   { "SizeTop", 0x00000008 },
   { "SizeBottom", 0x00000009 },
   { "Crosshair", 0x0000000a },
   { "Sleep", 0x0000000b },
   { "Sizing", 0x0000000c },
   { "SplitVertical", 0x0000000d },
   { "SplitHorizontal", 0x0000000e },
   { "Magnifier", 0x0000000f },
   { "Hand", 0x00000010 },
   { "HandLeft", 0x00000011 },
   { "HandRight", 0x00000012 },
   { "Text", 0x00000013 },
   { "Paintbrush", 0x00000014 },
   { "Stop", 0x00000015 },
   { "Invisible", 0x00000016 },
   { "Custom", 0x00000017 },
   { "Draggable", 0x00000018 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceType[] = {
   { "Root", 0x00000001 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceDMF[] = {
   { "ScaledX", 0x00000001 },
   { "ScaledY", 0x00000002 },
   { "FixedX", 0x00000004 },
   { "FixedY", 0x00000008 },
   { "ScaledXOffset", 0x00000010 },
   { "ScaledYOffset", 0x00000020 },
   { "FixedXOffset", 0x00000040 },
   { "FixedYOffset", 0x00000080 },
   { "FixedHeight", 0x00000100 },
   { "FixedWidth", 0x00000200 },
   { "ScaledHeight", 0x00000400 },
   { "ScaledWidth", 0x00000800 },
   { "FixedDepth", 0x00001000 },
   { "ScaledDepth", 0x00002000 },
   { "FixedZ", 0x00004000 },
   { "ScaledZ", 0x00008000 },
   { "ScaledRadiusX", 0x00010000 },
   { "FixedRadiusX", 0x00020000 },
   { "ScaledCenterX", 0x00040000 },
   { "ScaledCenterY", 0x00080000 },
   { "FixedCenterX", 0x00100000 },
   { "FixedCenterY", 0x00200000 },
   { "StatusChangeH", 0x00400000 },
   { "StatusChangeV", 0x00800000 },
   { "ScaledRadiusY", 0x01000000 },
   { "FixedRadiusY", 0x02000000 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceALIGN[] = {
   { "Left", 0x00000001 },
   { "Right", 0x00000002 },
   { "Horizontal", 0x00000004 },
   { "Vertical", 0x00000008 },
   { "Center", 0x0000000c },
   { "Middle", 0x0000000c },
   { "Top", 0x00000010 },
   { "Bottom", 0x00000020 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceJTYPE[] = {
   { "Secondary", 0x00000001 },
   { "Anchored", 0x00000002 },
   { "Dragged", 0x00000004 },
   { "Crossing", 0x00000008 },
   { "Digital", 0x00000010 },
   { "Analog", 0x00000020 },
   { "ExtMovement", 0x00000040 },
   { "Button", 0x00000080 },
   { "Movement", 0x00000100 },
   { "DblClick", 0x00000200 },
   { "Repeated", 0x00000400 },
   { "DragItem", 0x00000800 },
   { NULL, 0 }
};

static const struct FieldDef clSurfaceJET[] = {
   { "Button1", 0x00000001 },
   { "Lmb", 0x00000001 },
   { "Button2", 0x00000002 },
   { "Rmb", 0x00000002 },
   { "Button3", 0x00000003 },
   { "Mmb", 0x00000003 },
   { "Button4", 0x00000004 },
   { "Button5", 0x00000005 },
   { "Button6", 0x00000006 },
   { "Button7", 0x00000007 },
   { "Button8", 0x00000008 },
   { "Button9", 0x00000009 },
   { "Button10", 0x0000000a },
   { "Wheel", 0x0000000b },
   { "WheelTilt", 0x0000000c },
   { "PenTiltXY", 0x0000000d },
   { "AbsXY", 0x0000000e },
   { "CrossedIn", 0x0000000f },
   { "CrossedOut", 0x00000010 },
   { "Pressure", 0x00000011 },
   { "DeviceTiltXY", 0x00000012 },
   { "DeviceTiltZ", 0x00000013 },
   { "DisplayEdge", 0x00000014 },
   { NULL, 0 }
};

FDEF maInheritedFocus[] = { { "FocusID", FD_OBJECTID }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maExposeToDisplay[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maInvalidateRegion[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { 0, 0 } };
FDEF maSetDisplay[] = { { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { "InsideWidth", FD_LONG }, { "InsideHeight", FD_LONG }, { "BitsPerPixel", FD_LONG }, { "RefreshRate", FD_DOUBLE }, { "Flags", FD_LONG }, { 0, 0 } };
FDEF maSetOpacity[] = { { "Value", FD_DOUBLE }, { "Adjustment", FD_DOUBLE }, { 0, 0 } };
FDEF maAddCallback[] = { { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maResetDimensions[] = { { "X", FD_DOUBLE }, { "Y", FD_DOUBLE }, { "XOffset", FD_DOUBLE }, { "YOffset", FD_DOUBLE }, { "Width", FD_DOUBLE }, { "Height", FD_DOUBLE }, { "Dimensions", FD_LONG }, { 0, 0 } };
FDEF maRemoveCallback[] = { { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };

static const struct MethodEntry clSurfaceMethods[] = {
   { AC(-1), (APTR)SURFACE_InheritedFocus, "InheritedFocus", maInheritedFocus, sizeof(struct drw::InheritedFocus) },
   { AC(-2), (APTR)SURFACE_ExposeToDisplay, "ExposeToDisplay", maExposeToDisplay, sizeof(struct drw::ExposeToDisplay) },
   { AC(-3), (APTR)SURFACE_InvalidateRegion, "InvalidateRegion", maInvalidateRegion, sizeof(struct drw::InvalidateRegion) },
   { AC(-4), (APTR)SURFACE_SetDisplay, "SetDisplay", maSetDisplay, sizeof(struct drw::SetDisplay) },
   { AC(-5), (APTR)SURFACE_SetOpacity, "SetOpacity", maSetOpacity, sizeof(struct drw::SetOpacity) },
   { AC(-6), (APTR)SURFACE_AddCallback, "AddCallback", maAddCallback, sizeof(struct drw::AddCallback) },
   { AC(-7), (APTR)SURFACE_Minimise, "Minimise", 0, 0 },
   { AC(-8), (APTR)SURFACE_ResetDimensions, "ResetDimensions", maResetDimensions, sizeof(struct drw::ResetDimensions) },
   { AC(-9), (APTR)SURFACE_RemoveCallback, "RemoveCallback", maRemoveCallback, sizeof(struct drw::RemoveCallback) },
   { AC(-10), (APTR)SURFACE_ScheduleRedraw, "ScheduleRedraw", 0, 0 },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clSurfaceActions[] = {
   { AC::Activate, SURFACE_Activate },
   { AC::Disable, SURFACE_Disable },
   { AC::Draw, SURFACE_Draw },
   { AC::Enable, SURFACE_Enable },
   { AC::Focus, SURFACE_Focus },
   { AC::Free, SURFACE_Free },
   { AC::Hide, SURFACE_Hide },
   { AC::Init, SURFACE_Init },
   { AC::LostFocus, SURFACE_LostFocus },
   { AC::Move, SURFACE_Move },
   { AC::MoveToBack, SURFACE_MoveToBack },
   { AC::MoveToFront, SURFACE_MoveToFront },
   { AC::MoveToPoint, SURFACE_MoveToPoint },
   { AC::NewObject, SURFACE_NewObject },
   { AC::NewOwner, SURFACE_NewOwner },
   { AC::Redimension, SURFACE_Redimension },
   { AC::Resize, SURFACE_Resize },
   { AC::SaveImage, SURFACE_SaveImage },
   { AC::Show, SURFACE_Show },
   { AC::NIL, NULL }
};

