// Auto-generated by idl-c.fluid

FDEF maReadClientMsg[] = { { "Message", FD_PTR|FD_RESULT }, { "Length", FD_LONG|FD_RESULT }, { "Progress", FD_LONG|FD_RESULT }, { "CRC", FD_LONG|FD_RESULT }, { 0, 0 } };
FDEF maWriteClientMsg[] = { { "Message", FD_BUFFER|FD_PTR }, { "Length", FD_LONG|FD_BUFSIZE }, { 0, 0 } };

static const struct MethodEntry clClientSocketMethods[] = {
   { AC(-1), (APTR)CLIENTSOCKET_ReadClientMsg, "ReadClientMsg", maReadClientMsg, sizeof(struct cs::ReadClientMsg) },
   { AC(-2), (APTR)CLIENTSOCKET_WriteClientMsg, "WriteClientMsg", maWriteClientMsg, sizeof(struct cs::WriteClientMsg) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clClientSocketActions[] = {
   { AC::Free, CLIENTSOCKET_Free },
   { AC::Init, CLIENTSOCKET_Init },
   { AC::Read, CLIENTSOCKET_Read },
   { AC::Write, CLIENTSOCKET_Write },
   { AC::NIL, NULL }
};

