
const CSTRING glMessages[int(ERR::END)+1] = {
 "Operation successful.",
 "The result is false.",
 "Limited success.",
 "Operation cancelled.",
 "There is nothing to process.",
 "Please continue processing.",
 "Skip this operation.",
 "Retry the operation (could not succeed at this time).",
 "The folder is empty.",
 "Termination requested.",
 "Not enough memory available.",
 "Required pointer not present.",
 "Resource is in use.",
 "General failure.",
 "File error, e.g. file not found.",
 "There is an error in the provided data.",
 "A search routine in this function failed.",
 "Trouble initialising/using a module.",
 "File not found.",
 "Wrong version, or version not supported.",
 "Invalid arguments passed to function.",
 "No data is available for use.",
 "Error reading data.",
 "Error writing data.",
 "Failed to lock a required resource.",
 "Could not examine folder or file.",
 "The object has lost its class reference.",
 "The object does not support this operation.",
 "Operation not supported.",
 "General memory error.",
 "Function timed-out before successful completion.",
 "This object has lost its stats structure.",
 "Array is at low capacity.",
 "Error in Init()ialising an object.",
 "General security violation.",
 "System corruption detected.",
 "A container is needed to operate correctly.",
 "Container needs a Bitmap field.",
 "A newer version of the Core is required.",
 "The Width and/or Height field values need to be set.",
 "Module validation has failed.",
 "Process creation has failed.",
 "Class name not provided.",
 "A value is outside of the valid range.",
 "A call to ObtainMethod() failed.",
 "Array has reached capacity and cannot be expanded.",
 "Attempt to Query() failed.",
 "The object has lost its container.",
 "Do not expunge yet.",
 "The memory block is corrupt.",
 "I could not find the field that you requested.",
 "Invalid file or folder path detected.",
 "An unspecific error occurred during a SetField() operation.",
 "A resource cannot be accessed as it is marked for deletion.",
 "Illegal method ID (outside of valid range).",
 "Illegal action ID (outside of valid range).",
 "Module failed in its Open routine.",
 "Illegal attempt to execute an action on an object that belongs to another Task.",
 "The ModEntry->Header is missing.",
 "Module has not defined support for Init().",
 "Module failed its Initialisation routine.",
 "Memory block does not exist.",
 "Dead-lock detected - procedure aborted.",
 "Part of the system is unreachable due to a persistent lock.",
 "Module has not declared an official name.",
 "An error occurred while creating a new class.",
 "Error while Activate()ing an object.",
 "Warning - Attempt to initialise an object twice.",
 "A required field value is undefined.",
 "The class could not be found in the system.",
 "The File flag FL::READ was not set on initialisation.",
 "The File flag FL::WRITE was not set on initialisation.",
 "An error occurred while drawing the object.",
 "The class does not export any methods.",
 "No matching object was found for the given object ID.",
 "Access to a shared memory block was denied.",
 "The object is missing a setting in the Path or Location field.",
 "A lock was expected but not found.",
 "The search yielded no results.",
 "The tested statement was not satisfied.",
 "The object structure is corrupt or has not been initialised.",
 "Container pass through notification.",
 "The owner is not supported by this object.",
 "An attempt to gain exclusive access to a shared object failed.",
 "AllocMemory() failed to create a new memory block.",
 "NewObject() failed to produce a new object.",
 "GetField() failed to retrieve a field value.",
 "Access to a field was denied.",
 "ResolvePath() failed to resolve the path because it is a virtual reference.",
 "A dimension specification is invalid.",
 "Field type mismatch while getting or setting a field.",
 "A field type ID (e.g. INT, FLOAT) is not recognised.",
 "A buffer overflow has occurred.",
 "The specified field is not supported by the object's class.",
 "A mis-match has been detected that prevents further processing.",
 "An out-of-bounds error has occurred.",
 "An error occurred during a seek operation.",
 "The reallocation of a memory block failed.",
 "An infinite loop was detected.",
 "The destination file or folder already exists.",
 "A volume could not be resolved.",
 "A call to CreateObject() failed.",
 "Failed to obtain information on a memory block (MemoryInfo() failed).",
 "The object has not been initialised.",
 "A new resource could not be created because a matching resource exists.",
 "An attempt to Refresh() an object failed.",
 "An error occurred in a call to ListChildren().",
 "A call to the host system has failed.",
 "The size of the mask is smaller than the source Bitmap's dimensions.",
 "A required string value contains no characters.",
 "Object exists.",
 "The operation expected a path to a file.",
 "Failure during the resize of an object.",
 "Failure during the redimensioning of an object.",
 "A semaphore operation has failed.",
 "Field validation has failed.",
 "A new file could not be created.",
 "Deletion of a folder or file failed (e.g. permissions, read-only media).",
 "The file could not be opened.",
 "A delete or write operation failed due to read-only status.",
 "Resource does not exist.",
 "The destination path is the same as the source path.",
 "Resource exists.",
 "A sanity check failed.",
 "Out of space.  There is no available room to complete the request.",
 "GetSurfaceInfo() failed.",
 "Operation finished.",
 "Invalid syntax detected.",
 "Object was in an incorrect state for the operation.",
 "The Internet host name could not be resolved.",
 "Invalid Uniform Resource Identifier.",
 "The remote host refused the connection.",
 "The network was unreachable.",
 "No route to host.",
 "The connection between client and server was terminated.",
 "Task/Process still exists and is running.",
 "Referential integrity / constraint violation.",
 "Record changes would violate the DB schema.",
 "The size of a data chunk or buffer is incorrect.",
 "Operation cannot complete because system is busy with an earlier operation.",
 "Attempt to connect to server aborted.",
 "Function call missing argument value(s)",
 "An object is not of the required type.",
 "Execution violation - function must be called from the task that owns the object.",
 "Detected a recursive function call.",
 "Address pointer is outside of the task's memory map.",
 "The XML tags do not balance.",
 "The requested operation would block if it were performed at this time.",
 "Unspecified I/O error.",
 "Failed to load a module binary.",
 "A required handle is invalid.",
 "Unspecified security violation.",
 "A required value was not within expected constraints.",
 "The required service is not available.",
 "The object must be activated with the Activate action.",
 "A lock is required before accessing this functionality.",
 "Object or resource has already been locked.",
 "No media is inserted in the device.",
 "The requested smart card reader is in use.",
 "Failed to establish an SSL connection with the proxy server.",
 "A valid HTTP response was not received from the server.",
 "The reference is invalid.",
 "An exception was caught.",
 "Cannot execute a thread that is already running.",
 "Failure has been reported from OpenGL.",
 "An operation has been attempted that is only possible from within the main thread.",
 "Requested to use a registered sub-class (not an error).",
 "The expected type was not provided.",
 "Thread objects must be locked prior to activation.",
 "A message queue operation has failed.",
 "A call to SetVolume() failed.",
 "Unspecified failure during decompression of a data stream.",
 "Unspecified failure during compression of a data stream.",
 "The operation expected a folder path.",
 "This operation would violate the object's immutable status.",
 "A call to ReadFileToBuffer() failed.",
 "This feature is no longer available (obsolete).",
 "Failed to create a new resource.",
 "It is not possible to perform the requested operation.",
 "Failed to resolve a linked library symbol.",
 "A function call failed.",
 "Attempted to change a value that cannot be redefined.",
 "Attempted to set a numeric field with an incompatible value.",
 "Attempted to set a string field with an incompatible value.",
 "Attempted to set an object field with an incompatible value.",
 "Attempted to set a function field with an incompatible value.",
 "Attempted to set a pointer field with an incompatible value.",
 "Attempted to set an array field with an incompatible value.",
 "Attempted to set a lookup field with an incompatible value.",
 "The type of a value is invalid.",
 "A compression stream operation has failed.",
 "Task or process execution has failed.",
 "The compression data is invalid or corrupted.",
 "A sanity check has failed.",
 "Client is not authorised to perform this operation.",
 nullptr // Needs to be null-terminated for Fluid support
};

const int glTotalMessages = std::ssize(glMessages);
