// Auto-generated by idl-c.fluid

#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsSetVariable[] = { { "Error", FD_INT|FD_ERROR }, { "Script", FD_OBJECTPTR }, { "Name", FD_STR }, { "Type", FD_INT }, { "Variable", FD_TAGS }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)fl::SetVariable, "SetVariable", argsSetVariable },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "c.JOF:ALL_TIPS=0x20,DIAGNOSE=0x1,DUMP_BYTECODE=0x2,PROFILE=0x4,TIPS=0x10,TOP_TIPS=0x8,TRACE=0x7fc0,TRACE_ASSIGNMENTS=0x2000,TRACE_BOUNDARY=0x400,TRACE_CFG=0x40,TRACE_EXPECT=0x200,TRACE_OPERATORS=0x800,TRACE_REGISTERS=0x1000,TRACE_TOKENS=0x100,TRACE_TYPES=0x80,TRACE_VALUE_CATEGORY=0x4000\n"
