// Auto-generated by idl-c.fluid

#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsSetVariable[] = { { "Error", FD_INT|FD_ERROR }, { "Script", FD_OBJECTPTR }, { "Name", FD_STR }, { "Type", FD_INT }, { "Variable", FD_TAGS }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)fl::SetVariable, "SetVariable", argsSetVariable },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "c.JOF:DIAGNOSE=0x1,DUMP_BYTECODE=0x2,PROFILE=0x4,TRACE=0xff8,TRACE_ASSIGNMENTS=0x200,TRACE_BOUNDARY=0x20,TRACE_CFG=0x100,TRACE_EXPECT=0x10,TRACE_OPERATORS=0x40,TRACE_REGISTERS=0x80,TRACE_TOKENS=0x8,TRACE_TYPES=0x800,TRACE_VALUE_CATEGORY=0x400\n"
