// Auto-generated by idl-c.fluid

#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsSetVariable[] = { { "Error", FD_INT|FD_ERROR }, { "Script", FD_OBJECTPTR }, { "Name", FD_STR }, { "Type", FD_INT }, { "Variable", FD_TAGS }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)fl::SetVariable, "SetVariable", argsSetVariable },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "c.JOF:DIAGNOSE=0x1,DUMP_BYTECODE=0x20,LEGACY=0x2,PROFILE=0x40,TRACE_BOUNDARY=0x10,TRACE_EXPECT=0x8,TRACE_TOKENS=0x4\n"
