// Auto-generated by idl-c.fluid

static const struct FieldDef clButtonFlags[] = {
   { "NoGfx", 0x00000004 },
   { "Pulse", 0x00000080 },
   { "Sunken", 0x00000020 },
   { "Hide", 0x00000001 },
   { "NoFocusGfx", 0x00000100 },
   { "Disabled", 0x00000002 },
   { "NoBkgd", 0x00000008 },
   { "FadeBorder", 0x00000010 },
   { "NoFocus", 0x00000040 },
   { NULL, 0 }
};

static const struct ActionArray clButtonActions[] = {
   { AC_ActionNotify, (APTR)BUTTON_ActionNotify },
   { AC_Activate, (APTR)BUTTON_Activate },
   { AC_DataFeed, (APTR)BUTTON_DataFeed },
   { AC_Disable, (APTR)BUTTON_Disable },
   { AC_Enable, (APTR)BUTTON_Enable },
   { AC_Focus, (APTR)BUTTON_Focus },
   { AC_Free, (APTR)BUTTON_Free },
   { AC_Hide, (APTR)BUTTON_Hide },
   { AC_Init, (APTR)BUTTON_Init },
   { AC_Move, (APTR)BUTTON_Move },
   { AC_MoveToBack, (APTR)BUTTON_MoveToBack },
   { AC_MoveToFront, (APTR)BUTTON_MoveToFront },
   { AC_MoveToPoint, (APTR)BUTTON_MoveToPoint },
   { AC_NewObject, (APTR)BUTTON_NewObject },
   { AC_Redimension, (APTR)BUTTON_Redimension },
   { AC_Resize, (APTR)BUTTON_Resize },
   { AC_Show, (APTR)BUTTON_Show },
   { 0, 0 }
};

