// Auto-generated by idl-c.fluid

static const struct FieldDef clFileViewFlags[] = {
   { "ShowParent", 0x00000001 },
   { "NoFiles", 0x00000008 },
   { "SysKeys", 0x00000004 },
   { "NoExtensions", 0x00000002 },
   { "TotalRefresh", 0x00000010 },
   { NULL, 0 }
};

static const struct FieldDef clFileViewAuto[] = {
   { "Open", 0x00000001 },
   { "Edit", 0x00000002 },
   { "View", 0x00000003 },
   { NULL, 0 }
};

static const struct FieldDef clFileViewEventMask[] = {
   { "Location", 0x00000001 },
   { NULL, 0 }
};

FDEF maCopyFilesTo[] = { { "Dest", FD_STR }, { 0, 0 } };
FDEF maMoveFilesTo[] = { { "Dest", FD_STR }, { 0, 0 } };
FDEF maCreateShortcut[] = { { "Message", FD_STR }, { "Shortcut", FD_STR }, { "Path", FD_STR }, { 0, 0 } };

static const struct MethodArray clFileViewMethods[] = {
   { -1, (APTR)FILEVIEW_ParentDir, "ParentDir", 0, 0 },
   { -2, (APTR)FILEVIEW_CutFiles, "CutFiles", 0, 0 },
   { -3, (APTR)FILEVIEW_CopyFiles, "CopyFiles", 0, 0 },
   { -4, (APTR)FILEVIEW_PasteFiles, "PasteFiles", 0, 0 },
   { -5, (APTR)FILEVIEW_DeleteFiles, "DeleteFiles", 0, 0 },
   { -6, (APTR)FILEVIEW_CreateDir, "CreateDir", 0, 0 },
   { -7, (APTR)FILEVIEW_RenameFile, "RenameFile", 0, 0 },
   { -8, (APTR)FILEVIEW_EditFiles, "EditFiles", 0, 0 },
   { -9, (APTR)FILEVIEW_ViewFiles, "ViewFiles", 0, 0 },
   { -10, (APTR)FILEVIEW_CopyFilesTo, "CopyFilesTo", maCopyFilesTo, sizeof(struct fvCopyFilesTo) },
   { -11, (APTR)FILEVIEW_MoveFilesTo, "MoveFilesTo", maMoveFilesTo, sizeof(struct fvMoveFilesTo) },
   { -12, (APTR)FILEVIEW_OpenFiles, "OpenFiles", 0, 0 },
   { -13, (APTR)FILEVIEW_CreateShortcut, "CreateShortcut", maCreateShortcut, sizeof(struct fvCreateShortcut) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clFileViewActions[] = {
   { AC_ActionNotify, (APTR)FILEVIEW_ActionNotify },
   { AC_Activate, (APTR)FILEVIEW_Activate },
   { AC_Clear, (APTR)FILEVIEW_Clear },
   { AC_DataFeed, (APTR)FILEVIEW_DataFeed },
   { AC_Free, (APTR)FILEVIEW_Free },
   { AC_Init, (APTR)FILEVIEW_Init },
   { AC_NewObject, (APTR)FILEVIEW_NewObject },
   { AC_Refresh, (APTR)FILEVIEW_Refresh },
   { 0, 0 }
};

