// Auto-generated by idl-c.fluid

FDEF maSetDistantLight[] = { { "Azimuth", FD_DOUBLE }, { "Elevation", FD_DOUBLE }, { 0, 0 } };
FDEF maSetPointLight[] = { { "X", FD_DOUBLE }, { "Y", FD_DOUBLE }, { "Z", FD_DOUBLE }, { 0, 0 } };
FDEF maSetSpotLight[] = { { "X", FD_DOUBLE }, { "Y", FD_DOUBLE }, { "Z", FD_DOUBLE }, { "PX", FD_DOUBLE }, { "PY", FD_DOUBLE }, { "PZ", FD_DOUBLE }, { "Exponent", FD_DOUBLE }, { "ConeAngle", FD_DOUBLE }, { 0, 0 } };

static const struct MethodEntry clLightingFXMethods[] = {
   { AC(-20), (APTR)LIGHTINGFX_SetDistantLight, "SetDistantLight", maSetDistantLight, sizeof(struct lt::SetDistantLight) },
   { AC(-22), (APTR)LIGHTINGFX_SetPointLight, "SetPointLight", maSetPointLight, sizeof(struct lt::SetPointLight) },
   { AC(-21), (APTR)LIGHTINGFX_SetSpotLight, "SetSpotLight", maSetSpotLight, sizeof(struct lt::SetSpotLight) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clLightingFXActions[] = {
   { AC::Draw, LIGHTINGFX_Draw },
   { AC::Free, LIGHTINGFX_Free },
   { AC::NewPlacement, LIGHTINGFX_NewPlacement },
   { AC::NIL, NULL }
};

