// Auto-generated by idl-c.fluid

static const struct ActionArray clCompositeFXActions[] = {
   { AC_Draw, (APTR)COMPOSITEFX_Draw },
   { AC_Init, (APTR)COMPOSITEFX_Init },
   { AC_NewObject, (APTR)COMPOSITEFX_NewObject },
   { 0, 0 }
};

