// Auto-generated by idl-c.fluid

static const struct ActionArray clDisplacementFXActions[] = {
   { AC_Draw, (APTR)DISPLACEMENTFX_Draw },
   { AC_NewObject, (APTR)DISPLACEMENTFX_NewObject },
   { 0, 0 }
};

