// Auto-generated by idl-c.tiri

static const struct ActionArray clMorphologyFXActions[] = {
   { AC::Draw, MORPHOLOGYFX_Draw },
   { AC::NewObject, MORPHOLOGYFX_NewObject },
   { AC::NIL, nullptr }
};

