// Auto-generated by idl-c.fluid

static const struct ActionArray clTurbulenceFXActions[] = {
   { AC_Draw, TURBULENCEFX_Draw },
   { AC_Init, TURBULENCEFX_Init },
   { AC_NewObject, TURBULENCEFX_NewObject },
   { 0, NULL }
};

