// Auto-generated by idl-c.fluid

static const struct ActionArray clColourFXActions[] = {
   { AC::Draw, COLOURFX_Draw },
   { AC::Free, COLOURFX_Free },
   { AC::Init, COLOURFX_Init },
   { AC::NewObject, COLOURFX_NewObject },
   { AC::NIL, nullptr }
};

