// Auto-generated by idl-c.fluid

static const struct ActionArray clTurbulenceFXActions[] = {
   { AC_Draw, (APTR)TURBULENCEFX_Draw },
   { AC_Init, (APTR)TURBULENCEFX_Init },
   { AC_NewObject, (APTR)TURBULENCEFX_NewObject },
   { 0, 0 }
};

