// Auto-generated by idl-c.fluid

FDEF maSelectGamma[] = { { "Component", FD_LONG }, { "Amplitude", FD_DOUBLE }, { "Offset", FD_DOUBLE }, { "Exponent", FD_DOUBLE }, { 0, 0 } };
FDEF maSelectTable[] = { { "Component", FD_LONG }, { "Values", FD_ARRAY|FD_DOUBLE }, { "Size", FD_LONG|FD_ARRAYSIZE }, { 0, 0 } };
FDEF maSelectLinear[] = { { "Component", FD_LONG }, { "Slope", FD_DOUBLE }, { "Intercept", FD_DOUBLE }, { 0, 0 } };
FDEF maSelectIdentity[] = { { "Component", FD_LONG }, { 0, 0 } };
FDEF maSelectDiscrete[] = { { "Component", FD_LONG }, { "Values", FD_ARRAY|FD_DOUBLE }, { "Size", FD_LONG|FD_ARRAYSIZE }, { 0, 0 } };
FDEF maSelectInvert[] = { { "Component", FD_LONG }, { 0, 0 } };
FDEF maSelectMask[] = { { "Component", FD_LONG }, { "Mask", FD_LONG }, { 0, 0 } };

static const struct MethodEntry clRemapFXMethods[] = {
   { -20, (APTR)REMAPFX_SelectGamma, "SelectGamma", maSelectGamma, sizeof(struct rf::SelectGamma) },
   { -21, (APTR)REMAPFX_SelectTable, "SelectTable", maSelectTable, sizeof(struct rf::SelectTable) },
   { -22, (APTR)REMAPFX_SelectLinear, "SelectLinear", maSelectLinear, sizeof(struct rf::SelectLinear) },
   { -23, (APTR)REMAPFX_SelectIdentity, "SelectIdentity", maSelectIdentity, sizeof(struct rf::SelectIdentity) },
   { -24, (APTR)REMAPFX_SelectDiscrete, "SelectDiscrete", maSelectDiscrete, sizeof(struct rf::SelectDiscrete) },
   { -25, (APTR)REMAPFX_SelectInvert, "SelectInvert", maSelectInvert, sizeof(struct rf::SelectInvert) },
   { -26, (APTR)REMAPFX_SelectMask, "SelectMask", maSelectMask, sizeof(struct rf::SelectMask) },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clRemapFXActions[] = {
   { AC_Draw, REMAPFX_Draw },
   { AC_Free, REMAPFX_Free },
   { AC_NewObject, REMAPFX_NewObject },
   { 0, NULL }
};

