// Auto-generated by idl-c.fluid

static const struct ActionArray clMergeFXActions[] = {
   { AC::Draw, MERGEFX_Draw },
   { AC::Free, MERGEFX_Free },
   { AC::NewPlacement, MERGEFX_NewPlacement },
   { AC::NIL, nullptr }
};

