// Auto-generated by idl-c.fluid

static const struct ActionArray clWaveFunctionFXActions[] = {
   { AC::Draw, WAVEFUNCTIONFX_Draw },
   { AC::Free, WAVEFUNCTIONFX_Free },
   { AC::Init, WAVEFUNCTIONFX_Init },
   { AC::NewObject, WAVEFUNCTIONFX_NewObject },
   { AC::NIL, nullptr }
};

