// Auto-generated by idl-c.fluid

static const struct FieldDef clVectorFilterUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { NULL, 0 }
};

static const struct FieldDef clVectorFilterPrimitiveUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { NULL, 0 }
};

static const struct FieldDef clVectorFilterColourSpace[] = {
   { "SRGB", 0x00000001 },
   { "LinearRGB", 0x00000002 },
   { "Inherit", 0x00000003 },
   { NULL, 0 }
};

static const struct ActionArray clVectorFilterActions[] = {
   { AC_Clear, (APTR)VECTORFILTER_Clear },
   { AC_DataFeed, (APTR)VECTORFILTER_DataFeed },
   { AC_Free, (APTR)VECTORFILTER_Free },
   { AC_Init, (APTR)VECTORFILTER_Init },
   { AC_NewObject, (APTR)VECTORFILTER_NewObject },
   { 0, 0 }
};

