// Auto-generated by idl-c.fluid

static const struct ActionArray clCompositeFXActions[] = {
   { AC_Draw, COMPOSITEFX_Draw },
   { AC_Init, COMPOSITEFX_Init },
   { AC_NewObject, COMPOSITEFX_NewObject },
   { 0, NULL }
};

