// Auto-generated by idl-c.fluid

static const struct ActionArray clNetClientActions[] = {
   { AC::Free, NETCLIENT_Free },
   { AC::Init, NETCLIENT_Init },
   { AC::NewPlacement, NETCLIENT_NewPlacement },
   { AC::NIL, nullptr }
};

