// Auto-generated by idl-c.fluid

static const struct FieldDef clSVGFlags[] = {
   { "Autoscale", 0x00000001 },
   { "Alpha", 0x00000002 },
   { "EnforceTracking", 0x00000004 },
   { NULL, 0 }
};

FDEF maRender[] = { { "Bitmap", FD_OBJECTPTR }, { "X", FD_LONG }, { "Y", FD_LONG }, { "Width", FD_LONG }, { "Height", FD_LONG }, { 0, 0 } };
FDEF maParseSymbol[] = { { "ID", FD_STR }, { "Viewport", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clSVGMethods[] = {
   { AC(-1), (APTR)SVG_Render, "Render", maRender, sizeof(struct svg::Render) },
   { AC(-2), (APTR)SVG_ParseSymbol, "ParseSymbol", maParseSymbol, sizeof(struct svg::ParseSymbol) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clSVGActions[] = {
   { AC::Activate, SVG_Activate },
   { AC::DataFeed, SVG_DataFeed },
   { AC::Deactivate, SVG_Deactivate },
   { AC::Free, SVG_Free },
   { AC::Init, SVG_Init },
   { AC::NewPlacement, SVG_NewPlacement },
   { AC::SaveImage, SVG_SaveImage },
   { AC::SaveToObject, SVG_SaveToObject },
   { AC::NIL, NULL }
};

