// Auto-generated by idl-c.fluid

static const struct FieldDef clScrollbarFlags[] = {
   { "Constant", 0x00000002 },
   { "Relative", 0x00000004 },
   { "Hide", 0x00000001 },
   { "Slider", 0x00000008 },
   { "NoIntersect", 0x00000010 },
   { NULL, 0 }
};

static const struct FieldDef clScrollbarDirection[] = {
   { "Horizontal", 0x00000001 },
   { "Vertical", 0x00000002 },
   { NULL, 0 }
};

static const struct ActionArray clScrollbarActions[] = {
   { AC_ActionNotify, (APTR)SCROLLBAR_ActionNotify },
   { AC_Free, (APTR)SCROLLBAR_Free },
   { AC_Hide, (APTR)SCROLLBAR_Hide },
   { AC_Init, (APTR)SCROLLBAR_Init },
   { AC_NewObject, (APTR)SCROLLBAR_NewObject },
   { AC_Redimension, (APTR)SCROLLBAR_Redimension },
   { AC_Resize, (APTR)SCROLLBAR_Resize },
   { AC_Show, (APTR)SCROLLBAR_Show },
   { 0, 0 }
};

