#!/bin/bash
# Parasol Debian Package Builder
# This script builds .deb packages for Parasol Framework

set -e -u -o pipefail

# Enable debug mode if DEBUG environment variable is set
[[ "${DEBUG:-}" == "1" ]] && set -x

# Default values
BUILD_DIR="build-deb"
INSTALL_INCLUDES="OFF"
CLEAN_BUILD="no"
SIGN_PACKAGE="no"

# Function to show usage
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -h, --help              Show this help message"
    echo "  -c, --clean             Clean build directory before building"
    echo "  -d, --dev               Build development package (includes headers)"
    echo "  -s, --sign              Sign the package (requires GPG setup)"
    echo "  -b, --build-dir DIR     Use custom build directory (default: build-deb)"
    echo ""
    echo "Examples:"
    echo "  $0                      Build runtime package only"
    echo "  $0 --dev               Build both runtime and development packages"
    echo "  $0 --clean --dev       Clean build and create both packages"
}

# Parse command line arguments with input validation
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -c|--clean)
            CLEAN_BUILD="yes"
            shift
            ;;
        -d|--dev)
            INSTALL_INCLUDES="ON"
            shift
            ;;
        -s|--sign)
            SIGN_PACKAGE="yes"
            shift
            ;;
        -b|--build-dir)
            if [[ -z "${2:-}" ]]; then
                echo "Error: --build-dir requires a directory argument"
                exit 1
            fi
            # Sanitize build directory path
            BUILD_DIR="$(realpath -m "$2")"
            if [[ "$BUILD_DIR" =~ [\;\&\|\`\$] ]]; then
                echo "Error: Build directory path contains invalid characters"
                exit 1
            fi
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Check for required tools
if ! command -v dpkg-deb &> /dev/null; then
    echo "Error: dpkg-deb is required but not installed."
    echo "Install it with: sudo apt install dpkg-dev"
    exit 1
fi

if ! command -v cmake &> /dev/null; then
    echo "Error: cmake is required but not installed."
    exit 1
fi

# Get version from CMakeLists.txt with validation
if [ ! -f "CMakeLists.txt" ]; then
    echo "Error: CMakeLists.txt not found in current directory"
    echo "Please run this script from the Parasol source root directory"
    exit 1
fi

VERSION=$(grep "project (Parasol VERSION" CMakeLists.txt | sed 's/.*VERSION \([0-9.]*\).*/\1/' || true)
if [ -z "$VERSION" ] || [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Could not extract valid version from CMakeLists.txt"
    echo "Expected format: project (Parasol VERSION x.y.z)"
    exit 1
fi

# Detect architecture
ARCH=$(dpkg --print-architecture)

echo "Building Parasol Debian packages..."
echo "Version: $VERSION"
echo "Architecture: $ARCH"
echo "Build directory: $BUILD_DIR"
echo "Include headers: $INSTALL_INCLUDES"

# Clean build directory if requested
if [ "$CLEAN_BUILD" = "yes" ]; then
    echo "Cleaning build directory..."
    rm -rf "$BUILD_DIR"
fi

# Create build directory
mkdir -p "$BUILD_DIR"

# Configure CMake with Debian package generation
echo "Configuring CMake..."
cmake -S . -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DGENERATE_DEBIAN_PKG=ON \
    -DPARASOL_STATIC=OFF \
    -DRUN_ANYWHERE=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_DEFS=OFF \
    -DINSTALL_EXAMPLES=OFF \
    -DINSTALL_INCLUDES="$INSTALL_INCLUDES" \
    -DINSTALL_TESTS=OFF

# Build the project with error checking
echo "Building project..."
# Validate and use nproc with fallback
JOBS=$(nproc 2>/dev/null || echo "4")
if ! [[ "$JOBS" =~ ^[0-9]+$ ]] || [ "$JOBS" -eq 0 ]; then
    echo "Warning: Invalid nproc output, using default of 4 jobs"
    JOBS=4
fi

if ! cmake --build "$BUILD_DIR" --config Release -j "$JOBS"; then
    echo "Error: Build failed. Check build output above for details."
    exit 1
fi

# Create staging directories for packages
RUNTIME_STAGING="$BUILD_DIR/debian/parasol"
DEV_STAGING="$BUILD_DIR/debian/parasol-dev"

echo "Creating package staging directories..."
rm -rf "$RUNTIME_STAGING" "$DEV_STAGING"
mkdir -p "$RUNTIME_STAGING/DEBIAN" "$RUNTIME_STAGING/usr"

if [ "$INSTALL_INCLUDES" = "ON" ]; then
    mkdir -p "$DEV_STAGING/DEBIAN" "$DEV_STAGING/usr"
fi

# Install to staging directory with error checking
echo "Installing to staging directory..."
if ! DESTDIR="$RUNTIME_STAGING" cmake --install "$BUILD_DIR"; then
    echo "Error: Installation failed"
    exit 1
fi

# Copy debian control files for runtime package
# Copy control file if it exists (generated by CMake)
if [ -f "$BUILD_DIR/debian/control" ]; then
    cp "$BUILD_DIR/debian/control" "$RUNTIME_STAGING/DEBIAN/" || { echo "Failed to copy control file"; exit 1; }
fi
if [ ! -d "$RUNTIME_STAGING/usr/share/doc/parasol/" ]; then
    mkdir -p "$RUNTIME_STAGING/usr/share/doc/parasol/" || { echo "Failed to create directory $RUNTIME_STAGING/usr/share/doc/parasol/"; exit 1; }
fi
# Copy documentation files if they exist
if [ -f "$BUILD_DIR/debian/copyright" ]; then
    cp "$BUILD_DIR/debian/copyright" "$RUNTIME_STAGING/usr/share/doc/parasol/" || { echo "Failed to copy copyright file"; exit 1; }
fi
if [ -f "$BUILD_DIR/debian/changelog" ]; then
    cp "$BUILD_DIR/debian/changelog" "$RUNTIME_STAGING/usr/share/doc/parasol/" || { echo "Failed to copy changelog file"; exit 1; }
fi

# Copy maintainer scripts if they exist
for script in postinst prerm postrm; do
    if [ -f "pkg/debian/${script}.in" ]; then
        cp "pkg/debian/${script}.in" "$RUNTIME_STAGING/DEBIAN/${script}" || { echo "Warning: Failed to copy ${script} script"; }
        chmod 755 "$RUNTIME_STAGING/DEBIAN/${script}" 2>/dev/null || true
    fi
done

# Copy lintian overrides if they exist
if [ -f "pkg/debian/parasol.lintian-overrides" ]; then
    mkdir -p "$RUNTIME_STAGING/usr/share/lintian/overrides"
    cp "pkg/debian/parasol.lintian-overrides" "$RUNTIME_STAGING/usr/share/lintian/overrides/parasol" || { echo "Warning: Failed to copy lintian overrides"; }
fi

# Create runtime package control file
cat > "$RUNTIME_STAGING/DEBIAN/control" << EOF
Package: parasol
Version: $VERSION-1
Section: graphics
Priority: optional
Architecture: $ARCH
Depends: libfreetype6, zlib1g, libasound2, libx11-6, libxext6, libxrandr2, libstdc++6
Maintainer: Parasol Framework Team <team@parasol-framework.org>
Description: Vector graphics engine and application framework
 Parasol is a vector graphics engine and application framework designed for
 creating scalable user interfaces. The framework automatically handles display
 resolution and scaling concerns, allowing developers to focus on application
 logic rather than display technicalities.
EOF

# Handle development package if requested
if [ "$INSTALL_INCLUDES" = "ON" ]; then
    echo "Setting up development package..."
    
    # Move headers and development files to dev package
    if [ -d "$RUNTIME_STAGING/usr/include" ]; then
        mkdir -p "$DEV_STAGING/usr"
        mv "$RUNTIME_STAGING/usr/include" "$DEV_STAGING/usr/"
    fi
    
    # Create dev package control file
    cat > "$DEV_STAGING/DEBIAN/control" << EOF
Package: parasol-dev
Version: $VERSION-1
Section: libdevel
Priority: optional
Architecture: $ARCH
Depends: parasol (= $VERSION-1), libfreetype6-dev, zlib1g-dev, libasound2-dev, libx11-dev, libxext-dev, libxrandr-dev
Maintainer: Parasol Framework Team <team@parasol-framework.org>
Description: Development files for Parasol framework
 This package contains the header files and development libraries needed
 to compile applications that use the Parasol framework.
EOF

    # Copy documentation to dev package
    mkdir -p "$DEV_STAGING/usr/share/doc/parasol-dev"
    cp "$BUILD_DIR/debian/copyright" "$DEV_STAGING/usr/share/doc/parasol-dev/"
    cp "$BUILD_DIR/debian/changelog" "$DEV_STAGING/usr/share/doc/parasol-dev/"
    
    # Copy lintian overrides for dev package if they exist
    if [ -f "pkg/debian/parasol-dev.lintian-overrides" ]; then
        mkdir -p "$DEV_STAGING/usr/share/lintian/overrides"
        cp "pkg/debian/parasol-dev.lintian-overrides" "$DEV_STAGING/usr/share/lintian/overrides/parasol-dev" || { echo "Warning: Failed to copy dev lintian overrides"; }
    fi
fi

# Build the packages
echo "Building .deb packages..."

# Build runtime package
RUNTIME_PACKAGE="parasol_${VERSION}-1_${ARCH}.deb"
dpkg-deb --build "$RUNTIME_STAGING" "$RUNTIME_PACKAGE"
echo "Created: $RUNTIME_PACKAGE"

# Build development package if requested
if [ "$INSTALL_INCLUDES" = "ON" ]; then
    DEV_PACKAGE="parasol-dev_${VERSION}-1_${ARCH}.deb"
    dpkg-deb --build "$DEV_STAGING" "$DEV_PACKAGE"
    echo "Created: $DEV_PACKAGE"
fi

# Sign packages if requested
if [ "$SIGN_PACKAGE" = "yes" ]; then
    if command -v dpkg-sig &> /dev/null; then
        echo "Signing packages..."
        dpkg-sig --sign builder "$RUNTIME_PACKAGE"
        if [ "$INSTALL_INCLUDES" = "ON" ]; then
            dpkg-sig --sign builder "$DEV_PACKAGE"
        fi
        echo "Packages signed successfully"
    else
        echo "Warning: dpkg-sig not found, packages not signed"
        echo "Install with: sudo apt install dpkg-sig"
    fi
fi

# Verify packages
echo "Verifying packages..."
dpkg-deb -I "$RUNTIME_PACKAGE"
if [ "$INSTALL_INCLUDES" = "ON" ]; then
    dpkg-deb -I "$DEV_PACKAGE"
fi

echo ""
echo "Debian packages built successfully!"
echo "Runtime package: $RUNTIME_PACKAGE"
if [ "$INSTALL_INCLUDES" = "ON" ]; then
    echo "Development package: $DEV_PACKAGE"
fi
echo ""
echo "To install:"
echo "  sudo dpkg -i $RUNTIME_PACKAGE"
if [ "$INSTALL_INCLUDES" = "ON" ]; then
    echo "  sudo dpkg -i $DEV_PACKAGE"
fi
echo ""
echo "To install dependencies if needed:"
echo "  sudo apt-get install -f"