// Auto-generated by idl-c.fluid

FDEF maFind[] = { { "Port", FD_LONG }, { "Enabled", FD_LONG }, { 0, 0 } };

static const struct MethodArray clProxyMethods[] = {
   { -1, (APTR)PROXY_Delete, "Delete", 0, 0 },
   { -2, (APTR)PROXY_Find, "Find", maFind, sizeof(struct prxFind) },
   { -3, (APTR)PROXY_FindNext, "FindNext", 0, 0 },
   { 0, 0, 0, 0, 0 }
};

static const struct ActionArray clProxyActions[] = {
   { AC_Disable, (APTR)PROXY_Disable },
   { AC_Enable, (APTR)PROXY_Enable },
   { AC_Free, (APTR)PROXY_Free },
   { AC_Init, (APTR)PROXY_Init },
   { AC_NewObject, (APTR)PROXY_NewObject },
   { AC_SaveSettings, (APTR)PROXY_SaveSettings },
   { 0, NULL }
};

