// Auto-generated by idl-c.fluid

namespace net {
extern ERR StrToAddress(CSTRING String, struct IPAddress * Address);
extern CSTRING AddressToStr(struct IPAddress * IPAddress);
extern uint32_t HostToShort(uint32_t Value);
extern uint32_t HostToLong(uint32_t Value);
extern uint32_t ShortToHost(uint32_t Value);
extern uint32_t LongToHost(uint32_t Value);
extern ERR SetSSL(objNetSocket * NetSocket, ...);

} // namespace
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsAddressToStr[] = { { "Result", FD_STR|FD_ALLOC }, { "IPAddress:IPAddress", FD_PTR|FD_STRUCT }, { 0, 0 } };
FDEF argsHostToLong[] = { { "Result", FD_LONG|FD_UNSIGNED }, { "Value", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF argsHostToShort[] = { { "Result", FD_LONG|FD_UNSIGNED }, { "Value", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF argsLongToHost[] = { { "Result", FD_LONG|FD_UNSIGNED }, { "Value", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF argsSetSSL[] = { { "Error", FD_LONG|FD_ERROR }, { "NetSocket", FD_OBJECTPTR }, { "Tags", FD_TAGS }, { 0, 0 } };
FDEF argsShortToHost[] = { { "Result", FD_LONG|FD_UNSIGNED }, { "Value", FD_LONG|FD_UNSIGNED }, { 0, 0 } };
FDEF argsStrToAddress[] = { { "Error", FD_LONG|FD_ERROR }, { "String", FD_STR }, { "IPAddress:Address", FD_PTR|FD_STRUCT }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)net::StrToAddress, "StrToAddress", argsStrToAddress },
   { (APTR)net::AddressToStr, "AddressToStr", argsAddressToStr },
   { (APTR)net::HostToShort, "HostToShort", argsHostToShort },
   { (APTR)net::HostToLong, "HostToLong", argsHostToLong },
   { (APTR)net::ShortToHost, "ShortToHost", argsShortToHost },
   { (APTR)net::LongToHost, "LongToHost", argsLongToHost },
   { (APTR)net::SetSSL, "SetSSL", argsSetSSL },
   { NULL, NULL, NULL }
};

#undef MOD_IDL
#define MOD_IDL "s.IPAddress:ulData[4],lType,lPad\ns.NetClient:cIP[8],pNext,pPrev,oNetSocket,oSockets,pClientData,lTotalSockets\nc.IPADDR:V4=0x0,V6=0x1\nc.NLF:NO_CACHE=0x1\nc.NSF:LOG_ALL=0x10,MULTI_CONNECT=0x4,SERVER=0x1,SSL=0x2,SYNCHRONOUS=0x8\nc.NSL:CONNECT=0x1\nc.NTC:CONNECTED=0x3,CONNECTING=0x1,CONNECTING_SSL=0x2,DISCONNECTED=0x0\nc.SCV:AKID_ISSUER_SERIAL_MISMATCH=0x1f,AKID_SKID_MISMATCH=0x1e,APPLICATION_VERIFICATION=0x32,CERT_CHAIN_TOO_LONG=0x16,CERT_HAS_EXPIRED=0xa,CERT_NOT_YET_VALID=0x9,CERT_REJECTED=0x1c,CERT_REVOKED=0x17,CERT_SIGNATURE_FAILURE=0x7,CERT_UNTRUSTED=0x1b,CRL_HAS_EXPIRED=0xc,CRL_NOT_YET_VALID=0xb,CRL_SIGNATURE_FAILURE=0x8,DEPTH_ZERO_SELF_SIGNED_CERT=0x12,ERROR_IN_CERT_NOT_AFTER_FIELD=0xe,ERROR_IN_CERT_NOT_BEFORE_FIELD=0xd,ERROR_IN_CRL_LAST_UPDATE_FIELD=0xf,ERROR_IN_CRL_NEXT_UPDATE_FIELD=0x10,INVALID_CA=0x18,INVALID_PURPOSE=0x1a,KEYUSAGE_NO_CERTSIGN=0x20,OK=0x0,OUT_OF_MEM=0x11,PATH_LENGTH_EXCEEDED=0x19,SELF_SIGNED_CERT_IN_CHAIN=0x13,SUBJECT_ISSUER_MISMATCH=0x1d,UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY=0x6,UNABLE_TO_DECRYPT_CERT_SIGNATURE=0x4,UNABLE_TO_DECRYPT_CRL_SIGNATURE=0x5,UNABLE_TO_GET_CRL=0x3,UNABLE_TO_GET_ISSUER_CERT=0x2,UNABLE_TO_GET_ISSUER_CERT_LOCALLY=0x14,UNABLE_TO_VERIFY_LEAF_SIGNATURE=0x15\n"
